In [1]:
import numpy as np
import pandas as pd

In [12]:
books=pd.read_csv('books.csv')# Some line of books.csv might have an error so we have to skip these lines

C:\Users\adila\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3441: DtypeWarning: Columns (3) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [13]:
books=pd.read_csv('books.csv',error_bad_lines=False,encoding='latin1')

C:\Users\adila\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3441: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version.


  exec(code_obj, self.user_global_ns, self.user_ns)

In [14]:
books

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...
...,...,...,...,...,...,...,...,...
271355,0440400988,There's a Bat in Bunk Five,Paula Danziger,1988,Random House Childrens Pub (Mm),http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...
271356,0525447644,From One to One Hundred,Teri Sloat,1991,Dutton Books,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...
271357,006008667X,Lily Dale : The True Story of the Town that Ta...,Christine Wicker,2004,HarperSanFrancisco,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...
271358,0192126040,Republic (World's Classics),Plato,1996,Oxford University Press,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...
271359,0767409752,A Guided Tour of Rene Descartes' Meditations o...,Christopher Biffle,2000,McGraw-Hill Humanities/Social Sciences/Languages,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...

In [15]:
books=books[['ISBN','Book-Title','Book-Author','Year-Of-Publication','Publisher']]
books

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company
...,...,...,...,...,...
271355,0440400988,There's a Bat in Bunk Five,Paula Danziger,1988,Random House Childrens Pub (Mm)
271356,0525447644,From One to One Hundred,Teri Sloat,1991,Dutton Books
271357,006008667X,Lily Dale : The True Story of the Town that Ta...,Christine Wicker,2004,HarperSanFrancisco
271358,0192126040,Republic (World's Classics),Plato,1996,Oxford University Press
271359,0767409752,A Guided Tour of Rene Descartes' Meditations o...,Christopher Biffle,2000,McGraw-Hill Humanities/Social Sciences/Languages

In [24]:
# Renaming the columns
books=books.rename(columns={'Book-Title':'title','Book-Author':'author','Year-Of-Publication':'year','Publisher':'publisher'})

In [25]:
books

,ISBN,title,author,year,publisher
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company
...,...,...,...,...,...
271355,0440400988,There's a Bat in Bunk Five,Paula Danziger,1988,Random House Childrens Pub (Mm)
271356,0525447644,From One to One Hundred,Teri Sloat,1991,Dutton Books
271357,006008667X,Lily Dale : The True Story of the Town that Ta...,Christine Wicker,2004,HarperSanFrancisco
271358,0192126040,Republic (World's Classics),Plato,1996,Oxford University Press
271359,0767409752,A Guided Tour of Rene Descartes' Meditations o...,Christopher Biffle,2000,McGraw-Hill Humanities/Social Sciences/Languages

In [28]:
books.isnull().sum()#Very small amount of null values so will remove them after other dataframe are done

ISBN         0
title        0
author       1
year         0
publisher    2
dtype: int64

In [35]:
users=pd.read_csv('Users.csv',error_bad_lines=False,encoding='latin1')

C:\Users\adila\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3441: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version.


  exec(code_obj, self.user_global_ns, self.user_ns)

In [36]:
users

        User-ID                            Location   Age
0             1                  nyc, new york, usa   NaN
1             2           stockton, california, usa  18.0
2             3     moscow, yukon territory, russia   NaN
3             4           porto, v.n.gaia, portugal  17.0
4             5  farnborough, hants, united kingdom   NaN
...         ...                                 ...   ...
278853   278854               portland, oregon, usa   NaN
278854   278855  tacoma, washington, united kingdom  50.0
278855   278856           brampton, ontario, canada   NaN
278856   278857           knoxville, tennessee, usa   NaN
278857   278858                dublin, n/a, ireland   NaN

[278858 rows x 3 columns]

In [37]:
users.rename(columns={'User-ID':'user_id','Location':'location','Age':'age'},inplace=True)

In [38]:
users

        user_id                            location   age
0             1                  nyc, new york, usa   NaN
1             2           stockton, california, usa  18.0
2             3     moscow, yukon territory, russia   NaN
3             4           porto, v.n.gaia, portugal  17.0
4             5  farnborough, hants, united kingdom   NaN
...         ...                                 ...   ...
278853   278854               portland, oregon, usa   NaN
278854   278855  tacoma, washington, united kingdom  50.0
278855   278856           brampton, ontario, canada   NaN
278856   278857           knoxville, tennessee, usa   NaN
278857   278858                dublin, n/a, ireland   NaN

[278858 rows x 3 columns]

In [39]:
ratings=pd.read_csv('Ratings.csv',error_bad_lines=True,encoding='latin1')

C:\Users\adila\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3441: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version.


  exec(code_obj, self.user_global_ns, self.user_ns)

In [40]:
ratings

         User-ID         ISBN  Book-Rating
0         276725   034545104X            0
1         276726   0155061224            5
2         276727   0446520802            0
3         276729   052165615X            3
4         276729   0521795028            6
...          ...          ...          ...
1149775   276704   1563526298            9
1149776   276706   0679447156            0
1149777   276709   0515107662           10
1149778   276721   0590442449           10
1149779   276723  05162443314            8

[1149780 rows x 3 columns]

In [44]:
ratings.rename(columns={"User-ID":'user_id',"Book-Rating":"rating"},inplace=True)

In [45]:
ratings

         user_id         ISBN  rating
0         276725   034545104X       0
1         276726   0155061224       5
2         276727   0446520802       0
3         276729   052165615X       3
4         276729   0521795028       6
...          ...          ...     ...
1149775   276704   1563526298       9
1149776   276706   0679447156       0
1149777   276709   0515107662      10
1149778   276721   0590442449      10
1149779   276723  05162443314       8

[1149780 rows x 3 columns]

In [55]:
ratings.user_id.nunique()

105283

In [51]:
books.shape

(271360, 5)

In [53]:
users.shape

(278858, 3)

In [54]:
ratings.shape

(1149780, 3)

### First Problem
This is a huge dataset but the problem is that there are many books which have no ratings or very few user have rated them.

So will try to remove the books which have less than 50 users review (Hyperparameter: Can choose any number of users)

### Second Problem
Will remove the users who have given less than 200 book reviews (Hyperparameter)

In [65]:
ratings.ISBN[ratings['rating']==0].value_counts()

0971880107     1921
0316666343      588
0060928336      412
0385504209      396
044023722X      366
               ...
0064461637        1
0078822246        1
013615302X        1
01400.5183X       1
0679752714        1
Name: ISBN, Length: 246724, dtype: int64

In [67]:
count=ratings.user_id.value_counts()
count

11676     13602
198711     7550
153662     6109
98391      5891
35859      5850
          ...
116180        1
116166        1
116154        1
116137        1
276723        1
Name: user_id, Length: 105283, dtype: int64

In [76]:
y=count[count>200].index
y

Int64Index([ 11676, 198711, 153662,  98391,  35859, 212898, 278418,  76352,
            110973, 235105,
            ...
            260183,  73681,  44296, 155916,   9856, 274808,  28634,  59727,
            268622, 188951],
           dtype='int64', length=899)

In [79]:
#Now we only want these users to be in our dataframe
ratings[ratings['user_id'].isin(y)]

         user_id        ISBN  rating
1456      277427  002542730X      10
1457      277427  0026217457       0
1458      277427  003008685X       8
1459      277427  0030615321       0
1460      277427  0060002050       0
...          ...         ...     ...
1147612   275970  3829021860       0
1147613   275970  4770019572       0
1147614   275970   896086097       0
1147615   275970  9626340762       8
1147616   275970  9626344990       0

[526356 rows x 3 columns]

In [80]:
ratings=ratings[ratings['user_id'].isin(y)]
ratings

         user_id        ISBN  rating
1456      277427  002542730X      10
1457      277427  0026217457       0
1458      277427  003008685X       8
1459      277427  0030615321       0
1460      277427  0060002050       0
...          ...         ...     ...
1147612   275970  3829021860       0
1147613   275970  4770019572       0
1147614   275970   896086097       0
1147615   275970  9626340762       8
1147616   275970  9626344990       0

[526356 rows x 3 columns]

In [82]:
# Rating records reduce from from 1149780 to 526356 by eliminating non-useful users
#Only 899 users writes 526356 review

In [83]:
#Now we will join books and ratings Dataframe

In [95]:
ratings_with_books=ratings.merge(books,on='ISBN')

In [96]:
ratings_with_books

,user_id,ISBN,rating,title,author,year,publisher
0,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc
1,3363,002542730X,0,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc
2,11676,002542730X,6,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc
3,12538,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc
4,13552,002542730X,0,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc
...,...,...,...,...,...,...,...
487666,275970,1892145022,0,Here Is New York,E. B. White,1999,Little Bookroom
487667,275970,1931868123,0,There's a Porcupine in My Outhouse: Misadventu...,Mike Tougias,2002,Capital Books (VA)
487668,275970,3411086211,10,Die Biene.,Sybil GrÃƒÂƒ?ÃƒÂ‚Ã‚Â¤fin SchÃƒÂƒ?ÃƒÂ‚Ã‚Â¶nfeldt,1993,"Bibliographisches Institut, Mannheim"
487669,275970,3829021860,0,The Penis Book,Joseph Cohen,1999,Konemann
487670,275970,4770019572,0,Musashi,Eiji Yoshikawa,1995,Kodansha International (JPN)

In [97]:
ratings_with_books.isnull().sum()

user_id      0
ISBN         0
rating       0
title        0
author       0
year         0
publisher    2
dtype: int64

In [99]:
books.shape

(271360, 5)

#### Points to be noted
1. ratings data frame records 526356, ratings_with_books records 487671    
2. books dataframe records 271360, ratings_with_books records 487671
3. So you can see records have decreased with respect to ratings data frame AS books DATAFRAME DON'T HAVE ALL BOOKS AS IN ratings DATAFRAME (THOSE BOOKS IN ratings DATAFRAME WHO WERE NOT IN books DATAFRAME WERE REMOVED) THAT IS WHY THE RECORDS DECREASED
4. So you can see records have increased with respect to books data frame

In [110]:
books.nunique()

ISBN         271360
title        242135
author       102023
year            202
publisher     16807
dtype: int64

In [113]:
ratings_with_books.nunique() # now a books ISBN number is repeated multiple time as multiple user have rated it.
#same for title and author etc....

user_id         899
ISBN         178018
rating           11
title        160269
author        67165
year            183
publisher     11008
dtype: int64

In [114]:
users

        user_id                            location   age
0             1                  nyc, new york, usa   NaN
1             2           stockton, california, usa  18.0
2             3     moscow, yukon territory, russia   NaN
3             4           porto, v.n.gaia, portugal  17.0
4             5  farnborough, hants, united kingdom   NaN
...         ...                                 ...   ...
278853   278854               portland, oregon, usa   NaN
278854   278855  tacoma, washington, united kingdom  50.0
278855   278856           brampton, ontario, canada   NaN
278856   278857           knoxville, tennessee, usa   NaN
278857   278858                dublin, n/a, ireland   NaN

[278858 rows x 3 columns]

### We will take into account only those book who have been rated by atleast 50 user

In [160]:
# If you want to do this by earlier method then before merging ""ratings=ratings[ratings['user_id'].isin(y)]""
# and books dataframe apply conditon on ISBN also as z=ratings['ISBN'].value_counts(), z=z[z>=50], z.index
# ratings=ratings[ratings['ISBN'].isin(z)]
# ratings.merge(books,on="ISBN")
number_rating=ratings_with_books.groupby('title')['rating'].count().reset_index()  
number_rating

                                                    title  rating
0        A Light in the Storm: The Civil War Diary of ...       2
1                                   Always Have Popsicles       1
2                    Apple Magic (The Collector's series)       1
3        Beyond IBM: Leadership Marketing and Finance ...       1
4        Clifford Visita El Hospital (Clifford El Gran...       1
...                                                   ...     ...
160264  ÃƒÂƒ?ÃƒÂ‚?ber die Pflicht zum Ungehorsam gegen den...       3
160265                                    ÃƒÂƒ?ÃƒÂ‚?lpiraten.       1
160266                   ÃƒÂƒ?ÃƒÂ‚?rger mit Produkt X. Roman.       1
160267                            ÃƒÂƒ?ÃƒÂ‚?stlich der Berge.       1
160268                                ÃƒÂƒ?ÃƒÂ‚?thique en toc       1

[160269 rows x 2 columns]

In [150]:
number_rating=number_rating.rename(columns={'rating':'number_of_ratings'})
number_rating

                                                    title  number_of_ratings
0        A Light in the Storm: The Civil War Diary of ...                  2
1                                   Always Have Popsicles                  1
2                    Apple Magic (The Collector's series)                  1
3        Beyond IBM: Leadership Marketing and Finance ...                  1
4        Clifford Visita El Hospital (Clifford El Gran...                  1
...                                                   ...                ...
160264  ÃƒÂƒ?ÃƒÂ‚?ber die Pflicht zum Ungehorsam gegen den...                  3
160265                                    ÃƒÂƒ?ÃƒÂ‚?lpiraten.                  1
160266                   ÃƒÂƒ?ÃƒÂ‚?rger mit Produkt X. Roman.                  1
160267                            ÃƒÂƒ?ÃƒÂ‚?stlich der Berge.                  1
160268                                ÃƒÂƒ?ÃƒÂ‚?thique en toc                  1

[160269 rows x 2 columns]

### Now we have to merge ot into the ratings_with_books Dataframe

In [151]:
ratings_with_books.head(2)

,user_id,ISBN,rating,title,author,year,publisher
0,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc
1,3363,002542730X,0,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc

In [152]:
final_df=ratings_with_books.merge(number_rating,on='title')

In [153]:
final_df

,user_id,ISBN,rating,title,author,year,publisher,number_of_ratings
0,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,82
1,3363,002542730X,0,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,82
2,11676,002542730X,6,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,82
3,12538,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,82
4,13552,002542730X,0,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,82
...,...,...,...,...,...,...,...,...
487666,275970,1892145022,0,Here Is New York,E. B. White,1999,Little Bookroom,1
487667,275970,1931868123,0,There's a Porcupine in My Outhouse: Misadventu...,Mike Tougias,2002,Capital Books (VA),1
487668,275970,3411086211,10,Die Biene.,Sybil GrÃƒÂƒ?ÃƒÂ‚Ã‚Â¤fin SchÃƒÂƒ?ÃƒÂ‚Ã‚Â¶nfeldt,1993,"Bibliographisches Institut, Mannheim",1
487669,275970,3829021860,0,The Penis Book,Joseph Cohen,1999,Konemann,1
487670,275970,4770019572,0,Musashi,Eiji Yoshikawa,1995,Kodansha International (JPN),1

In [154]:
ratings_with_books.shape,final_df.shape

((487671, 7), (487671, 8))

##### We will take into account only those book who have been rated by atleast 50 user

In [159]:
final_df=final_df[final_df['number_of_ratings']>=50]
final_df

,user_id,ISBN,rating,title,author,year,publisher,number_of_ratings
0,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,82
1,3363,002542730X,0,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,82
2,11676,002542730X,6,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,82
3,12538,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,82
4,13552,002542730X,0,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,82
...,...,...,...,...,...,...,...,...
236701,255489,0553579983,7,And Then You Die,Iris Johansen,1998,Bantam,50
236702,256407,0553579983,0,And Then You Die,Iris Johansen,1998,Bantam,50
236703,257204,0553579983,0,And Then You Die,Iris Johansen,1998,Bantam,50
236704,261829,0553579983,0,And Then You Die,Iris Johansen,1998,Bantam,50
236705,273979,0553579983,0,And Then You Die,Iris Johansen,1998,Bantam,50

In [172]:
#### If a same user have rated a book multiple times this can be bad for our model so we will clear the duplicates.
final_df=final_df.drop_duplicates(['title','user_id'])
final_df

,user_id,ISBN,rating,title,author,year,publisher,number_of_ratings
0,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,82
1,3363,002542730X,0,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,82
2,11676,002542730X,6,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,82
3,12538,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,82
4,13552,002542730X,0,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,82
...,...,...,...,...,...,...,...,...
236701,255489,0553579983,7,And Then You Die,Iris Johansen,1998,Bantam,50
236702,256407,0553579983,0,And Then You Die,Iris Johansen,1998,Bantam,50
236703,257204,0553579983,0,And Then You Die,Iris Johansen,1998,Bantam,50
236704,261829,0553579983,0,And Then You Die,Iris Johansen,1998,Bantam,50
236705,273979,0553579983,0,And Then You Die,Iris Johansen,1998,Bantam,50

In [175]:
final_df.nunique()# In ratings_with_books user_id: 899 and in final_df it decrease to user_id : 888
# As that was those users which rated on books , WHO WERE RATED BY LESS THAN 50 USERS

user_id               888
ISBN                 2144
rating                 11
title                 742
author                579
year                   75
publisher             357
number_of_ratings     130
dtype: int64

In [180]:
book_pivot=final_df.pivot_table(values='rating',
    index='title',
    columns='user_id')
book_pivot

user_id,254,2276,2766,2977,3363,3757,4017,4385,6242,6251,...,274004,274061,274301,274308,274808,275970,277427,277478,277639,278418
title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
1st to Die: A Novel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2nd Chance,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN
4 Blondes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84 Charing Cross Road,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,10.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,7.0,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
You Belong To Me,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
Zoya,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"\O\"" Is for Outlaw""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

##### fill NaN value

In [182]:
book_pivot.fillna(0,inplace=True)
book_pivot

user_id,254,2276,2766,2977,3363,3757,4017,4385,6242,6251,...,274004,274061,274301,274308,274808,275970,277427,277478,277639,278418
title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
84 Charing Cross Road,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,7.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
You Belong To Me,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [184]:
# As you can see this is a very sparse type Mostly filled with zeros.
# We don,t want to calculate distance from zeros as it will increse our computational load.

In [185]:
#So we will convert it into sparse_matrix  so that internally distance from zeros will not be calculated
from scipy.sparse import csr_matrix
book_sparse=csr_matrix(book_pivot)

In [187]:
list(book_sparse)

[<1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 28 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 47 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 34 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 13 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 25 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 26 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 15 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 25 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 5 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 11 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 11 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 7 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 11 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 11 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 16 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 34 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 14 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 15 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 11 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 23 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 54 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 10 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 31 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 9 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 12 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 54 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 11 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 29 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 12 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 23 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 34 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 15 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 29 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 6 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 23 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 8 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 12 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 17 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 21 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 8 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 24 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 12 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 28 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 22 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 8 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 24 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 22 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 8 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 20 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 30 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 11 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 54 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 19 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 12 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 26 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 26 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 23 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 30 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 14 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 27 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 19 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 21 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 13 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 36 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 23 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 16 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 36 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 21 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 5 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 14 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 12 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 36 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 21 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 17 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 15 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 23 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 29 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 14 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 9 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 16 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 11 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 27 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 17 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 19 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 21 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 13 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 12 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 21 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 19 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 13 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 21 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 14 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 18 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 13 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 14 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 84 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 22 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 14 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 25 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 4 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 14 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 12 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 21 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 25 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 14 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 11 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 23 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 11 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 22 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 17 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 23 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 23 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 27 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 9 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 19 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 19 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 9 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 19 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 10 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 13 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 24 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 22 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 6 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 9 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 42 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 24 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 25 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 11 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 9 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 21 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 18 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 29 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 10 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 27 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 9 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 25 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 24 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 14 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 22 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 14 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 25 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 10 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 13 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 11 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 13 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 14 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 14 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 11 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 14 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 7 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 13 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 5 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 9 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 17 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 24 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 10 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 16 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 12 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 18 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 52 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 29 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 15 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 23 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 15 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 7 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 25 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 10 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 42 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 10 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 16 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 17 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 25 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'

In [183]:
#Will use KNN(classification and regression) brother Nearest Neighbour Algorithm that do Clustering.

In [189]:
from sklearn.neighbors import NearestNeighbors

In [192]:
model=NearestNeighbors(algorithm='brute')#n_neighbors=5 hyperparameter
#algorithm='auto'  'auto' will attempt to decide the most appropriate algorithm   hyperparameter
#algorithm='brute' We instruct the algo to calculate distance of all the points and then decide neighbors

In [193]:
model.fit(book_sparse)

NearestNeighbors(algorithm='brute')

In [211]:
book_pivot.iloc[0,:].values.reshape(1,-1)

array([[ 9.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  8.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  9.,  0.,
         0.,  0.,  0.,  8.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  7.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  9.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        10.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  9.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  8.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.,
        10.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0., 10.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  9.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  9.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  7.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         9.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  9.,  0.,  0.,  0.,  0.,  0.,  0.,
         8.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  9.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  9.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  8.,  0.,  0.,  0.,  0.,
         0.,  0.,  7.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0., 10.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.]])

In [242]:
distances,suggestion=model.kneighbors(book_pivot.iloc[237,:].values.reshape(1, -1),n_neighbors=6)
#reshaping is must for our model to understand the data
#Neighbors=6 because 1 book will be the 237 book itself   AGAIN IT IS HYPERPARAMETER

In [243]:
distances#0----> book 237 distance from book 237

array([[ 0.        , 68.78953409, 69.5413546 , 72.64296249, 76.83098333,
        77.28518616]])

In [244]:
suggestion

array([[237, 240, 238, 241, 184, 536]], dtype=int64)

In [245]:
suggestion[0][0]

237

In [246]:
book_pivot.index[suggestion[0][0]]

'Harry Potter and the Chamber of Secrets (Book 2)'

In [275]:
# THE SUGGESTION FOR BOOK 237----> 'Harry Potter and the Chamber of Secrets (Book 2)' ARE
for i in range(len(suggestion)):
    print(book_pivot.index[suggestion[i]].values)

['Harry Potter and the Prisoner of Azkaban (Book 3)'
 'Harry Potter and the Goblet of Fire (Book 4)'
 "Harry Potter and the Sorcerer's Stone (Book 1)" 'Exclusive'
 'The Cradle Will Fall']

In [250]:
book_pivot.index[237]

'Harry Potter and the Chamber of Secrets (Book 2)'

In [258]:
book_pivot.loc['Harry Potter and the Chamber of Secrets (Book 2)',:]

user_id
254       9.0
2276      0.0
2766      0.0
2977      0.0
3363      0.0
         ...
275970    9.0
277427    0.0
277478    0.0
277639    0.0
278418    0.0
Name: Harry Potter and the Chamber of Secrets (Book 2), Length: 888, dtype: float64

In [266]:
book_pivot.index=='Harry Potter and the Chamber of Secrets (Book 2)'

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False])

In [272]:
#np.where()  IS A FUNCTION THAT EXTRACT THE Values which is true
np.where(book_pivot.index=='Harry Potter and the Chamber of Secrets (Book 2)')[0][0]

237

In [307]:
def suggest(book_name):
    book_index=np.where(book_pivot.index==book_name)[0][0]
    distances,suggestion=model.kneighbors(book_pivot.iloc[book_index,:].values.reshape(1, -1),n_neighbors=6)
    for i in range(len(suggestion)):
        return 'The suggestion for the books: '+ str(book_pivot.index[suggestion[0][0]])+' are',book_pivot.index[suggestion[i]].values[1:6]

In [308]:
suggest('Harry Potter and the Chamber of Secrets (Book 2)')

('The suggestion for the books: Harry Potter and the Chamber of Secrets (Book 2) are',
 array(['Harry Potter and the Prisoner of Azkaban (Book 3)',
        'Harry Potter and the Goblet of Fire (Book 4)',
        "Harry Potter and the Sorcerer's Stone (Book 1)", 'Exclusive',
        'The Cradle Will Fall'], dtype=object))

In [309]:
suggest('4 Blondes')

('The suggestion for the books: 4 Blondes are',
 array(['No Safe Place', 'Pleading Guilty', 'Long After Midnight',
        'Exclusive', 'Lake Wobegon days'], dtype=object))

#### Files to save as pickle

##### 1.book_pivot
##### 2.model (Nearest Neighbors)

In [319]:
import pickle
pickle.dump(book_pivot,open('book_pivot.pkl','wb'))

In [320]:
pickle.dump(model,open('model.pkl','wb'))

In [315]:
image=pd.read_csv('books.csv',error_bad_lines=False,encoding='latin1')
image

C:\Users\adila\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3441: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version.


  exec(code_obj, self.user_global_ns, self.user_ns)
C:\Users\adila\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3441: DtypeWarning: Columns (3) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...
...,...,...,...,...,...,...,...,...
271355,0440400988,There's a Bat in Bunk Five,Paula Danziger,1988,Random House Childrens Pub (Mm),http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...
271356,0525447644,From One to One Hundred,Teri Sloat,1991,Dutton Books,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...
271357,006008667X,Lily Dale : The True Story of the Town that Ta...,Christine Wicker,2004,HarperSanFrancisco,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...
271358,0192126040,Republic (World's Classics),Plato,1996,Oxford University Press,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...
271359,0767409752,A Guided Tour of Rene Descartes' Meditations o...,Christopher Biffle,2000,McGraw-Hill Humanities/Social Sciences/Languages,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...

In [428]:
image['Image-URL-M']

0         http://images.amazon.com/images/P/0195153448.0...
1         http://images.amazon.com/images/P/0002005018.0...
2         http://images.amazon.com/images/P/0060973129.0...
3         http://images.amazon.com/images/P/0374157065.0...
4         http://images.amazon.com/images/P/0393045218.0...
                                ...
271355    http://images.amazon.com/images/P/0440400988.0...
271356    http://images.amazon.com/images/P/0525447644.0...
271357    http://images.amazon.com/images/P/006008667X.0...
271358    http://images.amazon.com/images/P/0192126040.0...
271359    http://images.amazon.com/images/P/0767409752.0...
Name: Image-URL-M, Length: 271360, dtype: object

In [338]:
book_list=list(book_pivot.index.values)
book_list

['1984',
 '1st to Die: A Novel',
 '2nd Chance',
 '4 Blondes',
 '84 Charing Cross Road',
 'A Bend in the Road',
 'A Case of Need',
 'A Child Called \\It\\": One Child\'s Courage to Survive"',
 'A Civil Action',
 'A Cry In The Night',
 'A Darkness More Than Night',
 'A Day Late and a Dollar Short',
 'A Fine Balance',
 'A Great Deliverance',
 'A Heartbreaking Work of Staggering Genius',
 'A Is for Alibi (Kinsey Millhone Mysteries (Paperback))',
 'A Lesson Before Dying (Vintage Contemporaries (Paperback))',
 'A Man Named Dave: A Story of Triumph and Forgiveness',
 'A Man in Full',
 'A Map of the World',
 'A Painted House',
 'A Patchwork Planet',
 'A Prayer for Owen Meany',
 'A Thin Dark Line (Mysteries &amp; Horror)',
 "A Thousand Acres (Ballantine Reader's Circle)",
 'A Time to Kill',
 "A Virtuous Woman (Oprah's Book Club (Paperback))",
 'A Walk to Remember',
 'A Widow for One Year',
 'A Wrinkle In Time',
 'A Wrinkle in Time',
 'A Year in Provence',
 "ANGELA'S ASHES",
 'Abduction',
 'About a Boy',
 'Absolute Power',
 'Acceptable Risk',
 'Accident',
 'Airframe',
 'Alaska',
 'All Around the Town',
 'All Creatures Great and Small',
 'All I Really Need to Know',
 'All That Remains (Kay Scarpetta Mysteries (Paperback))',
 'All the Pretty Horses (The Border Trilogy, Vol 1)',
 'Along Came a Spider (Alex Cross Novels)',
 'American Gods',
 'And Then You Die',
 "Angela's Ashes (MMP) : A Memoir",
 "Angela's Ashes: A Memoir",
 'Angels',
 'Angels &amp; Demons',
 'Angus, Thongs and Full-Frontal Snogging: Confessions of Georgia Nicolson',
 'Animal Dreams',
 'Animal Farm',
 'Anne Frank: The Diary of a Young Girl',
 'Anne of Avonlea (Anne of Green Gables Novels (Paperback))',
 'Anne of Green Gables (Anne of Green Gables Novels (Paperback))',
 'Anne of the Island',
 'Artemis Fowl (Artemis Fowl, Book 1)',
 'Ashes to Ashes',
 'At Home in Mitford (The Mitford Years)',
 'Atonement : A Novel',
 'B Is for Burglar (Kinsey Millhone Mysteries (Paperback))',
 'Back Roads',
 'Bag of Bones',
 'Balzac and the Little Chinese Seamstress : A Novel',
 'Bastard Out of Carolina',
 'Beach House',
 'Beach Music',
 'Before I Say Good-Bye',
 'Bel Canto: A Novel',
 'Beloved',
 'Beloved (Plume Contemporary Fiction)',
 'Betrayal in Death',
 "Big Cherry Holler: A Big Stone Gap Novel (Ballantine Reader's Circle)",
 "Big Stone Gap: A Novel (Ballantine Reader's Circle)",
 'Big Trouble',
 'Billy Straight : A Novel',
 'Birthright',
 'Bittersweet',
 'Black House',
 'Black Notice',
 'Black and Blue',
 'Bleachers',
 'Blessings',
 'Blood Work',
 'Blue Diary',
 'Body of Evidence (Kay Scarpetta Mysteries (Paperback))',
 'Body of Lies',
 'Brave New World',
 'Breath, Eyes, Memory',
 'Breathing Lessons',
 'Bridge to Terabithia',
 'Bridget Jones : The Edge of Reason',
 "Bridget Jones's Diary",
 'Bridget Jones: The Edge of Reason',
 'By the Light of the Moon',
 'C Is for Corpse (Kinsey Millhone Mysteries (Paperback))',
 "CAT'S EYE",
 'Call of the Wild',
 'Carnal Innocence',
 'Carolina Moon',
 'Carrie',
 'Cat &amp; Mouse (Alex Cross Novels)',
 'Catering to Nobody',
 'Cause of Death',
 'Certain Prey',
 "Charlotte's Web (Trophy Newbery)",
 'Charming Billy',
 'Chicken Soup for the Soul (Chicken Soup for the Soul)',
 "Chicken Soup for the Woman's Soul (Chicken Soup for the Soul Series (Paper))",
 'Chocolat',
 'Choke',
 'Chosen Prey',
 'Christine',
 'Chromosome 6',
 'Circle of Friends',
 'Clear and Present Danger (Jack Ryan Novels)',
 'Cold Mountain',
 'Cold Mountain : A Novel',
 'Cold Sassy Tree',
 'Colony',
 'Coming Home',
 'Confessions of a Shopaholic (Summer Display Opportunity)',
 'Confessions of an Ugly Stepsister : A Novel',
 'Congo',
 'Contact',
 'Contagion',
 'Coraline',
 'Couplehood',
 'Cradle and All',
 'Crazy for You',
 'Cruel &amp; Unusual (Kay Scarpetta Mysteries (Paperback))',
 'Cry Wolf',
 'Cujo',
 'D Is for Deadbeat (Kinsey Millhone Mysteries (Paperback))',
 'Daddy',
 "Daddy's Little Girl",
 'Daisy Fay and the Miracle Man',
 'Dance upon the Air (Three Sisters Island Trilogy)',
 'Dances With Wolves',
 'Dangerous',
 'Dark Angel',
 'Dark Paradise',
 'Dark Rivers of the Heart',
 'Dawn (Cutler)',
 'Dead Run',
 'Death du Jour',
 'Debt of Honor (Jack Ryan Novels)',
 'Deception Point',
 'Deck the Halls (Holiday Classics)',
 'Degree of Guilt',
 'Deja Dead',
 'Desperation',
 'Devices and Desires',
 'Different Seasons',
 'Digital Fortress : A Thriller',
 'Disclosure',
 'Divine Secrets of the Ya-Ya Sisterhood: A Novel',
 'Dolores Claiborne',
 "Don't Stand Too Close to a Naked Man",
 "Don't Sweat the Small Stuff and It's All Small Stuff : Simple Ways to Keep the Little Things from Taking Over Your Life (Don't Sweat the Small Stuff Series)",
 "Dr. Atkins' New Diet Revolution",
 'Dragon Tears',
 'Dragonfly in Amber',
 'Dream Country',
 'Dreamcatcher',
 'Drowning Ruth',
 "Drowning Ruth (Oprah's Book Club)",
 'Drums of Autumn',
 "Dude, Where's My Country?",
 'Dust to Dust',
 'Dying for Chocolate (Culinary Mysteries (Paperback))',
 'E Is for Evidence: A Kinsey Millhone Mystery (Kinsey Millhone Mysteries (Paperback))',
 'Easy Prey',
 'Echoes',
 'Ellen Foster',
 'Empire Falls',
 "Ender's Game (Ender Wiggins Saga (Paperback))",
 'Engaging The Enemy',
 'Envy',
 'Evening Class',
 "Everything's Eventual : 14 Dark Tales",
 'Exclusive',
 'Executive Orders (Jack Ryan Novels)',
 'Eyes of Prey',
 'Eyes of a Child',
 'F Is for Fugitive (Kinsey Millhone Mysteries (Paperback))',
 'FORREST GUMP (Movie Tie in)',
 'Face the Fire (Three Sisters Island Trilogy)',
 'Fahrenheit 451',
 'Faking It',
 'Fall On Your Knees (Oprah #45)',
 'Falling Angels',
 'False Memory',
 'Family Album',
 'Fast Food Nation: The Dark Side of the All-American Meal',
 'Fast Women',
 'Fat Tuesday',
 'Fatal Cure',
 'Fatherhood',
 'Fear Nothing',
 'Final Target',
 'Fine Things',
 'Fingersmith',
 'Five Days in Paris',
 'Five Quarters of the Orange',
 'Flesh and Blood',
 'Forever... : A Novel of Good and Evil, Love and Hope',
 "Fortune's Rocks : A Novel",
 "Fortune's Rocks: A Novel",
 "Foucault's Pendulum",
 'Four Blind Mice',
 'Four Past Midnight',
 'Four To Score (A Stephanie Plum Novel)',
 'Fried Green Tomatoes at the Whistle Stop Cafe',
 "From Potter's Field",
 'From the Corner of His Eye',
 "Full House (Janet Evanovich's Full Series)",
 "Full Tilt (Janet Evanovich's Full Series)",
 'G Is for Gumshoe (Kinsey Millhone Mysteries (Paperback))',
 'GARDEN OF SHADOWS (Dollanger Saga (Paperback))',
 "Gerald's Game",
 'Girl in Hyacinth Blue',
 'Girl with a Pearl Earring',
 'Girl, Interrupted',
 'Good Omens',
 'Good in Bed',
 'Gorky Park',
 'Granny Dan',
 'Guardian Angel',
 'Guilty Pleasures (Anita Blake Vampire Hunter (Paperback))',
 'Guilty as Sin',
 'H Is for Homicide (Kinsey Millhone Mysteries (Paperback))',
 'Hannibal',
 'Hard Eight : A Stephanie Plum Novel (A Stephanie Plum Novel)',
 'Harry Potter and the Chamber of Secrets (Book 2)',
 'Harry Potter and the Goblet of Fire (Book 4)',
 'Harry Potter and the Order of the Phoenix (Book 5)',
 'Harry Potter and the Prisoner of Azkaban (Book 3)',
 "Harry Potter and the Sorcerer's Stone (Book 1)",
 "Harry Potter and the Sorcerer's Stone (Harry Potter (Paperback))",
 'Harvest',
 'Heart of the Sea (Irish Trilogy)',
 'Heartbeat',
 'Heartbreaker',
 'Hearts In Atlantis',
 'Hearts in Atlantis',
 'Heaven and Earth (Three Sisters Island Trilogy)',
 'Hemlock Bay',
 'Here on Earth',
 'Hide &amp; Seek',
 'Hideaway',
 'High Fidelity',
 'High Five (A Stephanie Plum Novel)',
 'Holes (Yearling Newbery)',
 'Homecoming',
 'Homeport',
 "Hornet's Nest",
 'Hot Six : A Stephanie Plum Novel (A Stephanie Plum Novel)',
 'House of Sand and Fog',
 'How Stella Got Her Groove Back',
 'How to Be Good',
 'How to Make an American Quilt',
 'I Capture the Castle',
 'I Is for Innocent',
 'I Know This Much Is True',
 "I Know This Much Is True (Oprah's Book Club)",
 'I Know Why the Caged Bird Sings',
 "I'll Be Seeing You",
 'Icebound',
 'Icy Sparks',
 'If Only It Were True',
 'If Tomorrow Comes',
 'Impulse',
 'In Her Shoes : A Novel',
 'Inner Harbor (Quinn Brothers (Paperback))',
 'Insomnia',
 'Intensity',
 'Interview with the Vampire',
 'Into Thin Air : A Personal Account of the Mt. Everest Disaster',
 'Into the Wild',
 'Invasion',
 'Irish Hearts',
 'Isle of Dogs',
 'It',
 'It Was on Fire When I Lay Down on It',
 "It's Always Something",
 'J Is for Judgment',
 'Jack &amp; Jill (Alex Cross Novels)',
 'Jacob Have I Loved',
 'Jemima J: A Novel About Ugly Ducklings and Swans',
 'Jewel',
 "Jewel (Oprah's Book Club)",
 'Jewels of the Sun (Irish Trilogy)',
 'Journey',
 'Jurassic Park',
 'K Is for Killer (Kinsey Millhone Mysteries (Paperback))',
 'Kaleidoscope',
 'Key of Knowledge (Key Trilogy (Paperback))',
 'Key of Light (Key Trilogy (Paperback))',
 'Key of Valor (Roberts, Nora. Key Trilogy, 3.)',
 'Killjoy',
 'Kiss the Girls',
 'L Is for Lawless',
 'Ladder of Years',
 'Lake Wobegon Days',
 'Lake Wobegon days',
 "Lamb : The Gospel According to Biff, Christ's Childhood Pal",
 'Last Chance Saloon',
 'Last Man Standing',
 "Left Behind: A Novel of the Earth's Last Days (Left Behind No. 1)",
 'Let Me Call You Sweetheart',
 'Life of Pi',
 'Lightning',
 'Like Water for Chocolate : A Novel in Monthly Installments with Recipes, Romances, and Home Remedies',
 'Like Water for Chocolate: A Novel in Monthly Installments With Recipes, Romances and Home Remedies',
 'Like Water for Chocolate: A Novel in Monthly Installments, With Recipes, Romances, and Home Remedies',
 'Little Altars Everywhere: A Novel',
 'Long After Midnight',
 'Lord of the Flies',
 'Love in the Time of Cholera (Penguin Great Books of the 20th Century)',
 'Loves Music, Loves to Dance',
 'Lucky : A Memoir',
 'Lucky Man: A Memoir',
 'M Is for Malice',
 'Macgregor Brides (Macgregors)',
 'Macgregor Grooms (Macgregors)',
 'Master of the Game',
 'Matilda',
 'Me Talk Pretty One Day',
 'Men Are from Mars, Women Are from Venus: A Practical Guide for Improving Communication and Getting What You Want in Your Relationships',
 'Mercy',
 'Message from Nam',
 'Message in a Bottle',
 'Middlesex: A Novel',
 'Midnight',
 'Midnight Bayou',
 'Midnight in the Garden of Good and Evil',
 'Midnight in the Garden of Good and Evil: A Savannah Story',
 'Midwives: A Novel',
 'Mind Prey',
 'Mirror Image',
 'Misery',
 'Miss Julia Speaks Her Mind : A Novel',
 'Monster : A Novel (Alex Delaware Novels (Paperback))',
 'Montana Sky',
 'Moo',
 'Moonlight Becomes You',
 'Morality for Beautiful Girls (No.1 Ladies Detective Agency)',
 'Mortal Fear',
 'Mortal Prey',
 'Mother of Pearl',
 'Mr. Murder',
 'My Gal Sunday',
 'Mystic River',
 'N Is for Noose',
 'Naked',
 'Needful Things',
 'Nerd in Shining Armor',
 'Neuromancer (Remembering Tomorrow)',
 'Neverwhere',
 'Nickel and Dimed: On (Not) Getting By in America',
 'Nicolae: The Rise of Antichrist (Left Behind No. 3)',
 'Night',
 'Night Prey',
 'Night Sins',
 'Night Whispers',
 'Nightmares &amp; Dreamscapes',
 'Nights in Rodanthe',
 'No Greater Love',
 'No Safe Place',
 'Notes from a Small Island',
 'Nothing Lasts Forever',
 'Now You See Her',
 'On the Street Where You Live',
 'One Door Away from Heaven',
 'One True Thing',
 'One for the Money (A Stephanie Plum Novel)',
 'One for the Money (Stephanie Plum Novels (Paperback))',
 'Oryx and Crake',
 'Outlander',
 'Over the Edge',
 'P Is for Peril',
 'Paradise',
 'Patriot Games (Jack Ryan Novels)',
 'Pay It Forward',
 'Peace Like a River',
 'Pet Sematary',
 'Phantoms',
 'Pigs in Heaven',
 'Plainsong (Vintage Contemporaries)',
 'Pleading Guilty',
 'Plum Island',
 'Point of Origin',
 'Politically Correct Bedtime Stories: Modern Tales for Our Life and Times',
 'Pop Goes the Weasel',
 'Portrait in Death',
 'Possession : A Romance',
 'Postmortem',
 'Practical Magic',
 'Presumed Innocent',
 "Pretend You Don't See Her",
 'Pride and Prejudice',
 'Primary Colors: A Novel of Politics',
 'Prime Cut',
 'Prodigal Summer',
 'Prodigal Summer: A Novel',
 'Purity in Death',
 'Q Is for Quarry',
 'Quentins',
 'Rainbow Six',
 'Range of Motion',
 'Reap the Wind',
 'Rebecca',
 'Red Dragon',
 'Red Storm Rising',
 'Remember Me',
 'Riptide',
 'Rising Sun',
 'Rising Tides',
 "River's End",
 'River, Cross My Heart',
 'Rose Madder',
 'Roses Are Red (Alex Cross Novels)',
 'Rules of Prey',
 'SHIPPING NEWS',
 'STONES FROM THE RIVER',
 'Sacred Sins',
 'Saint Maybe',
 'Sanctuary',
 'Saving Faith',
 'Scarlet Feather',
 'Scarlett : The Sequel to Margaret Mitchell\'s \\Gone With the Wind\\""',
 "Schindler's List",
 'Sea Glass: A Novel',
 'Sea Swept (Quinn Brothers (Paperback))',
 'Seabiscuit',
 'Seabiscuit: An American Legend',
 'Second Nature',
 'Secret History',
 'Secrets',
 'Seize the Night',
 'September',
 'Seven Habits Of Highly Effective People',
 'Seven Up (A Stephanie Plum Novel)',
 'Shadow Prey',
 'Shadowfires',
 'Shattered',
 "She's Come Undone (Oprah's Book Club (Paperback))",
 "She's Come Undone (Oprah's Book Club)",
 'Shell Seekers',
 'Shopaholic Takes Manhattan (Summer Display Opportunity)',
 'Shopaholic Ties the Knot',
 'Sick Puppy',
 'Silence of the Lambs',
 'Silent Witness',
 'Sisterhood of the Traveling Pants',
 'Skeleton Crew',
 'Skipping Christmas',
 'Slammerkin',
 "Slaughterhouse Five or the Children's Crusade: A Duty Dance With Death",
 'Sleepers',
 'Slow Waltz in Cedar Bend',
 'Small Town Girl',
 'Smart Women',
 "Smilla's Sense of Snow",
 'Snow Falling on Cedars',
 'Sole Survivor',
 "Song of Solomon (Oprah's Book Club (Paperback))",
 "Songs in Ordinary Time (Oprah's Book Club (Paperback))",
 "Sophie's World: A Novel About the History of Philosophy",
 'Southern Cross',
 'Sphere',
 'Standoff',
 'Stanislaski Brothers (Silhouette Promo)',
 'Still Waters',
 'Stillwatch',
 'Strangers',
 'Stupid White Men ...and Other Sorry Excuses for the State of the Nation!',
 'Sudden Prey',
 'Summer Pleasures',
 'Summer Sisters',
 "Suzanne's Diary for Nicholas",
 'Table For Two',
 'Tales of a Fourth Grade Nothing',
 'Taltos: Lives of the Mayfair Witches',
 'Tara Road',
 'Tears of the Giraffe (No.1 Ladies Detective Agency)',
 'Tears of the Moon (Irish Trilogy)',
 'Tell Me Lies (Tell Me Lies)',
 'Tell Me Your Dreams',
 'Tell No One',
 'Temptation',
 'That Camden Summer',
 'The Accidental Tourist',
 'The Alchemist: A Fable About Following Your Dream',
 'The Alibi',
 'The Alienist',
 'The Amazing Adventures of Kavalier &amp; Clay',
 'The Amber Spyglass (His Dark Materials, Book 3)',
 'The Andromeda Strain',
 'The Angel of Darkness',
 'The Apprentice',
 'The Bachelor (Warner Books Contemporary Romance)',
 'The Bad Beginning (A Series of Unfortunate Events, Book 1)',
 'The Bad Place',
 'The Beach House',
 'The Bean Trees',
 'The Blind Assassin',
 'The Blue Nowhere : A Novel',
 'The Bluest Eye',
 'The Body Farm',
 "The Bonesetter's Daughter",
 'The Bonfire of the Vanities',
 "The Book of Ruth (Oprah's Book Club (Paperback))",
 'The Bourne Identity',
 'The Bourne Supremacy',
 'The Bourne Ultimatum',
 'The Boy Next Door',
 'The Brethren',
 'The Bridges of Madison County',
 'The Burden of Proof',
 'The Cardinal of the Kremlin (Jack Ryan Novels)',
 'The Carousel',
 'The Catcher in the Rye',
 'The Celestine Prophecy (Celestine Prophecy)',
 'The Chamber',
 'The Cider House Rules',
 "The Clan of the Cave Bear (Earth's Children (Paperback))",
 'The Client',
 'The Clinic (Alex Delaware Novels (Paperback))',
 'The Color Purple',
 "The Color of Water: A Black Man's Tribute to His White Mother",
 'The Copper Beech',
 'The Cradle Will Fall',
 'The Crimson Petal and the White',
 'The Da Vinci Code',
 'The Dark Half',
 'The Dead Zone',
 'The Deep End of the Ocean',
 'The Devil Wears Prada : A Novel',
 'The Diary of Ellen Rimbauer: My Life at Rose Red',
 'The Divine Secrets of the Ya-Ya Sisterhood: A Novel',
 'The Dogs of Babel (Today Show Book Club #12)',
 'The Door to December',
 'The Drawing of the Three (The Dark Tower, Book 2)',
 'The Edge',
 'The Eight',
 'The Empty Chair',
 'The English Patient',
 'The Eyre Affair: A Novel',
 'The Face of Deception',
 'The Fellowship of the Ring (The Lord of the Rings, Part 1)',
 'The Firm',
 'The First Counsel',
 'The First Wives Club Movie Tie In',
 'The Five People You Meet in Heaven',
 'The Fourth Hand',
 "The General's Daughter",
 'The Genesis Code',
 'The Ghost',
 'The Gift',
 'The Girl Who Loved Tom Gordon',
 "The Girls' Guide to Hunting and Fishing",
 'The Giver (21st Century Reference)',
 'The Glass Lake',
 'The God of Small Things',
 'The Golden Compass (His Dark Materials, Book 1)',
 'The Great Gatsby',
 'The Green Mile',
 'The Grilling Season',
 'The Guardian',
 'The Gunslinger (The Dark Tower, Book 1)',
 "The Handmaid's Tale",
 "The Hitchhiker's Guide to the Galaxy",
 'The Hobbit : The Enchanting Prelude to The Lord of the Rings',
 'The Honk and Holler Opening Soon',
 'The Horse Whisperer',
 'The Hot Zone',
 'The Hours : A Novel',
 'The Hours: A Novel',
 'The House of the Spirits',
 'The Hundred Secret Senses',
 'The Hunt for Red October',
 "The Idiot Girls' Action Adventure Club",
 'The Jester',
 'The Joy Luck Club',
 'The Killing Game: Only One Can Win...and the Loser Dies',
 'The King of Torts',
 'The Kiss',
 "The Kitchen God's Wife",
 'The Last Precinct',
 'The Last Time They Met : A Novel',
 'The Little Friend',
 'The Little Prince',
 'The Long Road Home',
 'The Loop',
 "The Lost Boy: A Foster Child's Search for the Love of a Family",
 'The Lost World',
 'The Lottery Winner : Alvirah And Willy Stories',
 'The Lovely Bones: A Novel',
 'The Mists of Avalon',
 'The Most Wanted',
 'The Mulberry Tree',
 'The Mummy or Ramses the Damned',
 'The Murder Book',
 'The Nanny Diaries: A Novel',
 'The Next Accident',
 "The No. 1 Ladies' Detective Agency (Today Show Book Club #8)",
 'The Notebook',
 'The Other Boleyn Girl',
 'The Partner',
 'The Pelican Brief',
 'The Perfect Storm : A True Story of Men Against the Sea',
 'The Phantom Tollbooth',
 'The Pillars of the Earth',
 "The Pilot's Wife : A Novel",
 "The Plains of Passage (Earth's Children (Paperback))",
 'The Poisonwood Bible',
 'The Poisonwood Bible: A Novel',
 'The Prince of Tides',
 "The Princess Bride: S Morgenstern's Classic Tale of True Love and High Adventure",
 'The Promise',
 'The Pull of the Moon',
 'The Queen of the Damned (Vampire Chronicles (Paperback))',
 'The Rainmaker',
 'The Rapture of Canaan',
 'The Reader',
 'The Red Tent (Bestselling Backlist)',
 'The Reef',
 'The Regulators',
 'The Reptile Room (A Series of Unfortunate Events, Book 2)',
 'The Rescue',
 'The Return Journey',
 'The Return of the King (The Lord of the Rings, Part 3)',
 'The Robber Bride',
 'The Runaway Jury',
 'The Sands of Time',
 'The Saving Graces: A Novel',
 'The Search',
 'The Secret Garden',
 'The Secret Life of Bees',
 'The Shining',
 'The Shipping News : A Novel',
 'The Simple Truth',
 'The Smoke Jumper',
 'The Stone Diaries',
 'The Street Lawyer',
 'The Subtle Knife (His Dark Materials, Book 2)',
 'The Sum of All Fears (Jack Ryan Novels)',
 'The Summerhouse',
 'The Summons',
 'The Surgeon',
 "The Sweet Potato Queens' Book of Love",
 'The Switch',
 'The Tale of the Body Thief (Vampire Chronicles (Paperback))',
 'The Talisman',
 'The Tao of Pooh',
 'The Temple of My Familiar',
 'The Terminal Man',
 'The Testament',
 'The Thorn Birds',
 'The Tommyknockers',
 'The Two Towers (The Lord of the Rings, Part 2)',
 'The Ugly Duckling',
 'The Valley of Horses',
 'The Vampire Lestat (Vampire Chronicles, Book II)',
 'The Villa',
 'The Virgin Suicides',
 'The Wedding',
 'The Weight of Water : A Novel Tag: Author of Resistance and Strange Fits of Passion',
 'The Winner',
 'The Witching Hour (Lives of the Mayfair Witches)',
 'The Witness',
 'The Woman Next Door',
 'Thinner',
 'Three Fates',
 'Three Junes',
 'Three To Get Deadly : A Stephanie Plum Novel (A Stephanie Plum Novel)',
 'Timeline',
 'Tis : A Memoir',
 'Tis: A Memoir',
 'To Kill a Mockingbird',
 'To the Nines: A Stephanie Plum Novel',
 "Tom Clancy's Op-Center (Tom Clancy's Op Center (Paperback))",
 'Touching Evil',
 'Tough Cookie',
 'Toxin',
 'Tribulation Force: The Continuing Drama of Those Left Behind (Left Behind No. 2)',

In [339]:
len(book_list)

742

In [341]:
book_list=pd.DataFrame(book_list,columns=['title'])
book_list

                                                 title
0                                                 1984
1                                  1st to Die: A Novel
2                                           2nd Chance
3                                            4 Blondes
4                                84 Charing Cross Road
..                                                 ...
737                                    Year of Wonders
738                                   You Belong To Me
739  Zen and the Art of Motorcycle Maintenance: An ...
740                                               Zoya
741                                \O\" Is for Outlaw"

[742 rows x 1 columns]

In [344]:
book_list['title'].values

array(['1984', '1st to Die: A Novel', '2nd Chance', '4 Blondes',
       '84 Charing Cross Road', 'A Bend in the Road', 'A Case of Need',
       'A Child Called \\It\\": One Child\'s Courage to Survive"',
       'A Civil Action', 'A Cry In The Night',
       'A Darkness More Than Night', 'A Day Late and a Dollar Short',
       'A Fine Balance', 'A Great Deliverance',
       'A Heartbreaking Work of Staggering Genius',
       'A Is for Alibi (Kinsey Millhone Mysteries (Paperback))',
       'A Lesson Before Dying (Vintage Contemporaries (Paperback))',
       'A Man Named Dave: A Story of Triumph and Forgiveness',
       'A Man in Full', 'A Map of the World', 'A Painted House',
       'A Patchwork Planet', 'A Prayer for Owen Meany',
       'A Thin Dark Line (Mysteries &amp; Horror)',
       "A Thousand Acres (Ballantine Reader's Circle)", 'A Time to Kill',
       "A Virtuous Woman (Oprah's Book Club (Paperback))",
       'A Walk to Remember', 'A Widow for One Year', 'A Wrinkle In Time',
       'A Wrinkle in Time', 'A Year in Provence', "ANGELA'S ASHES",
       'Abduction', 'About a Boy', 'Absolute Power', 'Acceptable Risk',
       'Accident', 'Airframe', 'Alaska', 'All Around the Town',
       'All Creatures Great and Small', 'All I Really Need to Know',
       'All That Remains (Kay Scarpetta Mysteries (Paperback))',
       'All the Pretty Horses (The Border Trilogy, Vol 1)',
       'Along Came a Spider (Alex Cross Novels)', 'American Gods',
       'And Then You Die', "Angela's Ashes (MMP) : A Memoir",
       "Angela's Ashes: A Memoir", 'Angels', 'Angels &amp; Demons',
       'Angus, Thongs and Full-Frontal Snogging: Confessions of Georgia Nicolson',
       'Animal Dreams', 'Animal Farm',
       'Anne Frank: The Diary of a Young Girl',
       'Anne of Avonlea (Anne of Green Gables Novels (Paperback))',
       'Anne of Green Gables (Anne of Green Gables Novels (Paperback))',
       'Anne of the Island', 'Artemis Fowl (Artemis Fowl, Book 1)',
       'Ashes to Ashes', 'At Home in Mitford (The Mitford Years)',
       'Atonement : A Novel',
       'B Is for Burglar (Kinsey Millhone Mysteries (Paperback))',
       'Back Roads', 'Bag of Bones',
       'Balzac and the Little Chinese Seamstress : A Novel',
       'Bastard Out of Carolina', 'Beach House', 'Beach Music',
       'Before I Say Good-Bye', 'Bel Canto: A Novel', 'Beloved',
       'Beloved (Plume Contemporary Fiction)', 'Betrayal in Death',
       "Big Cherry Holler: A Big Stone Gap Novel (Ballantine Reader's Circle)",
       "Big Stone Gap: A Novel (Ballantine Reader's Circle)",
       'Big Trouble', 'Billy Straight : A Novel', 'Birthright',
       'Bittersweet', 'Black House', 'Black Notice', 'Black and Blue',
       'Bleachers', 'Blessings', 'Blood Work', 'Blue Diary',
       'Body of Evidence (Kay Scarpetta Mysteries (Paperback))',
       'Body of Lies', 'Brave New World', 'Breath, Eyes, Memory',
       'Breathing Lessons', 'Bridge to Terabithia',
       'Bridget Jones : The Edge of Reason', "Bridget Jones's Diary",
       'Bridget Jones: The Edge of Reason', 'By the Light of the Moon',
       'C Is for Corpse (Kinsey Millhone Mysteries (Paperback))',
       "CAT'S EYE", 'Call of the Wild', 'Carnal Innocence',
       'Carolina Moon', 'Carrie', 'Cat &amp; Mouse (Alex Cross Novels)',
       'Catering to Nobody', 'Cause of Death', 'Certain Prey',
       "Charlotte's Web (Trophy Newbery)", 'Charming Billy',
       'Chicken Soup for the Soul (Chicken Soup for the Soul)',
       "Chicken Soup for the Woman's Soul (Chicken Soup for the Soul Series (Paper))",
       'Chocolat', 'Choke', 'Chosen Prey', 'Christine', 'Chromosome 6',
       'Circle of Friends', 'Clear and Present Danger (Jack Ryan Novels)',
       'Cold Mountain', 'Cold Mountain : A Novel', 'Cold Sassy Tree',
       'Colony', 'Coming Home',
       'Confessions of a Shopaholic (Summer Display Opportunity)',
       'Confessions of an Ugly Stepsister : A Novel', 'Congo', 'Contact',
       'Contagion', 'Coraline', 'Couplehood', 'Cradle and All',
       'Crazy for You',
       'Cruel &amp; Unusual (Kay Scarpetta Mysteries (Paperback))',
       'Cry Wolf', 'Cujo',
       'D Is for Deadbeat (Kinsey Millhone Mysteries (Paperback))',
       'Daddy', "Daddy's Little Girl", 'Daisy Fay and the Miracle Man',
       'Dance upon the Air (Three Sisters Island Trilogy)',
       'Dances With Wolves', 'Dangerous', 'Dark Angel', 'Dark Paradise',
       'Dark Rivers of the Heart', 'Dawn (Cutler)', 'Dead Run',
       'Death du Jour', 'Debt of Honor (Jack Ryan Novels)',
       'Deception Point', 'Deck the Halls (Holiday Classics)',
       'Degree of Guilt', 'Deja Dead', 'Desperation',
       'Devices and Desires', 'Different Seasons',
       'Digital Fortress : A Thriller', 'Disclosure',
       'Divine Secrets of the Ya-Ya Sisterhood: A Novel',
       'Dolores Claiborne', "Don't Stand Too Close to a Naked Man",
       "Don't Sweat the Small Stuff and It's All Small Stuff : Simple Ways to Keep the Little Things from Taking Over Your Life (Don't Sweat the Small Stuff Series)",
       "Dr. Atkins' New Diet Revolution", 'Dragon Tears',
       'Dragonfly in Amber', 'Dream Country', 'Dreamcatcher',
       'Drowning Ruth', "Drowning Ruth (Oprah's Book Club)",
       'Drums of Autumn', "Dude, Where's My Country?", 'Dust to Dust',
       'Dying for Chocolate (Culinary Mysteries (Paperback))',
       'E Is for Evidence: A Kinsey Millhone Mystery (Kinsey Millhone Mysteries (Paperback))',
       'Easy Prey', 'Echoes', 'Ellen Foster', 'Empire Falls',
       "Ender's Game (Ender Wiggins Saga (Paperback))",
       'Engaging The Enemy', 'Envy', 'Evening Class',
       "Everything's Eventual : 14 Dark Tales", 'Exclusive',
       'Executive Orders (Jack Ryan Novels)', 'Eyes of Prey',
       'Eyes of a Child',
       'F Is for Fugitive (Kinsey Millhone Mysteries (Paperback))',
       'FORREST GUMP (Movie Tie in)',
       'Face the Fire (Three Sisters Island Trilogy)', 'Fahrenheit 451',
       'Faking It', 'Fall On Your Knees (Oprah #45)', 'Falling Angels',
       'False Memory', 'Family Album',
       'Fast Food Nation: The Dark Side of the All-American Meal',
       'Fast Women', 'Fat Tuesday', 'Fatal Cure', 'Fatherhood',
       'Fear Nothing', 'Final Target', 'Fine Things', 'Fingersmith',
       'Five Days in Paris', 'Five Quarters of the Orange',
       'Flesh and Blood',
       'Forever... : A Novel of Good and Evil, Love and Hope',
       "Fortune's Rocks : A Novel", "Fortune's Rocks: A Novel",
       "Foucault's Pendulum", 'Four Blind Mice', 'Four Past Midnight',
       'Four To Score (A Stephanie Plum Novel)',
       'Fried Green Tomatoes at the Whistle Stop Cafe',
       "From Potter's Field", 'From the Corner of His Eye',
       "Full House (Janet Evanovich's Full Series)",
       "Full Tilt (Janet Evanovich's Full Series)",
       'G Is for Gumshoe (Kinsey Millhone Mysteries (Paperback))',
       'GARDEN OF SHADOWS (Dollanger Saga (Paperback))', "Gerald's Game",
       'Girl in Hyacinth Blue', 'Girl with a Pearl Earring',
       'Girl, Interrupted', 'Good Omens', 'Good in Bed', 'Gorky Park',
       'Granny Dan', 'Guardian Angel',
       'Guilty Pleasures (Anita Blake Vampire Hunter (Paperback))',
       'Guilty as Sin',
       'H Is for Homicide (Kinsey Millhone Mysteries (Paperback))',
       'Hannibal',
       'Hard Eight : A Stephanie Plum Novel (A Stephanie Plum Novel)',
       'Harry Potter and the Chamber of Secrets (Book 2)',
       'Harry Potter and the Goblet of Fire (Book 4)',
       'Harry Potter and the Order of the Phoenix (Book 5)',
       'Harry Potter and the Prisoner of Azkaban (Book 3)',
       "Harry Potter and the Sorcerer's Stone (Book 1)",
       "Harry Potter and the Sorcerer's Stone (Harry Potter (Paperback))",
       'Harvest', 'Heart of the Sea (Irish Trilogy)', 'Heartbeat',
       'Heartbreaker', 'Hearts In Atlantis', 'Hearts in Atlantis',
       'Heaven and Earth (Three Sisters Island Trilogy)', 'Hemlock Bay',
       'Here on Earth', 'Hide &amp; Seek', 'Hideaway', 'High Fidelity',
       'High Five (A Stephanie Plum Novel)', 'Holes (Yearling Newbery)',
       'Homecoming', 'Homeport', "Hornet's Nest",
       'Hot Six : A Stephanie Plum Novel (A Stephanie Plum Novel)',
       'House of Sand and Fog', 'How Stella Got Her Groove Back',
       'How to Be Good', 'How to Make an American Quilt',
       'I Capture the Castle', 'I Is for Innocent',
       'I Know This Much Is True',
       "I Know This Much Is True (Oprah's Book Club)",
       'I Know Why the Caged Bird Sings', "I'll Be Seeing You",
       'Icebound', 'Icy Sparks', 'If Only It Were True',
       'If Tomorrow Comes', 'Impulse', 'In Her Shoes : A Novel',
       'Inner Harbor (Quinn Brothers (Paperback))', 'Insomnia',
       'Intensity', 'Interview with the Vampire',
       'Into Thin Air : A Personal Account of the Mt. Everest Disaster',
       'Into the Wild', 'Invasion', 'Irish Hearts', 'Isle of Dogs', 'It',
       'It Was on Fire When I Lay Down on It', "It's Always Something",
       'J Is for Judgment', 'Jack &amp; Jill (Alex Cross Novels)',
       'Jacob Have I Loved',
       'Jemima J: A Novel About Ugly Ducklings and Swans', 'Jewel',
       "Jewel (Oprah's Book Club)", 'Jewels of the Sun (Irish Trilogy)',
       'Journey', 'Jurassic Park',
       'K Is for Killer (Kinsey Millhone Mysteries (Paperback))',
       'Kaleidoscope', 'Key of Knowledge (Key Trilogy (Paperback))',
       'Key of Light (Key Trilogy (Paperback))',
       'Key of Valor (Roberts, Nora. Key Trilogy, 3.)', 'Killjoy',
       'Kiss the Girls', 'L Is for Lawless', 'Ladder of Years',
       'Lake Wobegon Days', 'Lake Wobegon days',
       "Lamb : The Gospel According to Biff, Christ's Childhood Pal",
       'Last Chance Saloon', 'Last Man Standing',
       "Left Behind: A Novel of the Earth's Last Days (Left Behind No. 1)",
       'Let Me Call You Sweetheart', 'Life of Pi', 'Lightning',
       'Like Water for Chocolate : A Novel in Monthly Installments with Recipes, Romances, and Home Remedies',
       'Like Water for Chocolate: A Novel in Monthly Installments With Recipes, Romances and Home Remedies',
       'Like Water for Chocolate: A Novel in Monthly Installments, With Recipes, Romances, and Home Remedies',
       'Little Altars Everywhere: A Novel', 'Long After Midnight',
       'Lord of the Flies',
       'Love in the Time of Cholera (Penguin Great Books of the 20th Century)',
       'Loves Music, Loves to Dance', 'Lucky : A Memoir',
       'Lucky Man: A Memoir', 'M Is for Malice',
       'Macgregor Brides (Macgregors)', 'Macgregor Grooms (Macgregors)',
       'Master of the Game', 'Matilda', 'Me Talk Pretty One Day',
       'Men Are from Mars, Women Are from Venus: A Practical Guide for Improving Communication and Getting What You Want in Your Relationships',
       'Mercy', 'Message from Nam', 'Message in a Bottle',
       'Middlesex: A Novel', 'Midnight', 'Midnight Bayou',
       'Midnight in the Garden of Good and Evil',
       'Midnight in the Garden of Good and Evil: A Savannah Story',
       'Midwives: A Novel', 'Mind Prey', 'Mirror Image', 'Misery',
       'Miss Julia Speaks Her Mind : A Novel',
       'Monster : A Novel (Alex Delaware Novels (Paperback))',
       'Montana Sky', 'Moo', 'Moonlight Becomes You',
       'Morality for Beautiful Girls (No.1 Ladies Detective Agency)',
       'Mortal Fear', 'Mortal Prey', 'Mother of Pearl', 'Mr. Murder',
       'My Gal Sunday', 'Mystic River', 'N Is for Noose', 'Naked',
       'Needful Things', 'Nerd in Shining Armor',
       'Neuromancer (Remembering Tomorrow)', 'Neverwhere',
       'Nickel and Dimed: On (Not) Getting By in America',
       'Nicolae: The Rise of Antichrist (Left Behind No. 3)', 'Night',
       'Night Prey', 'Night Sins', 'Night Whispers',
       'Nightmares &amp; Dreamscapes', 'Nights in Rodanthe',
       'No Greater Love', 'No Safe Place', 'Notes from a Small Island',
       'Nothing Lasts Forever', 'Now You See Her',
       'On the Street Where You Live', 'One Door Away from Heaven',
       'One True Thing', 'One for the Money (A Stephanie Plum Novel)',
       'One for the Money (Stephanie Plum Novels (Paperback))',
       'Oryx and Crake', 'Outlander', 'Over the Edge', 'P Is for Peril',
       'Paradise', 'Patriot Games (Jack Ryan Novels)', 'Pay It Forward',
       'Peace Like a River', 'Pet Sematary', 'Phantoms', 'Pigs in Heaven',
       'Plainsong (Vintage Contemporaries)', 'Pleading Guilty',
       'Plum Island', 'Point of Origin',
       'Politically Correct Bedtime Stories: Modern Tales for Our Life and Times',
       'Pop Goes the Weasel', 'Portrait in Death',
       'Possession : A Romance', 'Postmortem', 'Practical Magic',
       'Presumed Innocent', "Pretend You Don't See Her",
       'Pride and Prejudice', 'Primary Colors: A Novel of Politics',
       'Prime Cut', 'Prodigal Summer', 'Prodigal Summer: A Novel',
       'Purity in Death', 'Q Is for Quarry', 'Quentins', 'Rainbow Six',
       'Range of Motion', 'Reap the Wind', 'Rebecca', 'Red Dragon',
       'Red Storm Rising', 'Remember Me', 'Riptide', 'Rising Sun',
       'Rising Tides', "River's End", 'River, Cross My Heart',
       'Rose Madder', 'Roses Are Red (Alex Cross Novels)',
       'Rules of Prey', 'SHIPPING NEWS', 'STONES FROM THE RIVER',
       'Sacred Sins', 'Saint Maybe', 'Sanctuary', 'Saving Faith',
       'Scarlet Feather',
       'Scarlett : The Sequel to Margaret Mitchell\'s \\Gone With the Wind\\""',
       "Schindler's List", 'Sea Glass: A Novel',
       'Sea Swept (Quinn Brothers (Paperback))', 'Seabiscuit',
       'Seabiscuit: An American Legend', 'Second Nature',
       'Secret History', 'Secrets', 'Seize the Night', 'September',
       'Seven Habits Of Highly Effective People',
       'Seven Up (A Stephanie Plum Novel)', 'Shadow Prey', 'Shadowfires',
       'Shattered', "She's Come Undone (Oprah's Book Club (Paperback))",
       "She's Come Undone (Oprah's Book Club)", 'Shell Seekers',
       'Shopaholic Takes Manhattan (Summer Display Opportunity)',
       'Shopaholic Ties the Knot', 'Sick Puppy', 'Silence of the Lambs',
       'Silent Witness', 'Sisterhood of the Traveling Pants',
       'Skeleton Crew', 'Skipping Christmas', 'Slammerkin',
       "Slaughterhouse Five or the Children's Crusade: A Duty Dance With Death",
       'Sleepers', 'Slow Waltz in Cedar Bend', 'Small Town Girl',
       'Smart Women', "Smilla's Sense of Snow", 'Snow Falling on Cedars',
       'Sole Survivor', "Song of Solomon (Oprah's Book Club (Paperback))",
       "Songs in Ordinary Time (Oprah's Book Club (Paperback))",
       "Sophie's World: A Novel About the History of Philosophy",
       'Southern Cross', 'Sphere', 'Standoff',
       'Stanislaski Brothers (Silhouette Promo)', 'Still Waters',
       'Stillwatch', 'Strangers',
       'Stupid White Men ...and Other Sorry Excuses for the State of the Nation!',
       'Sudden Prey', 'Summer Pleasures', 'Summer Sisters',
       "Suzanne's Diary for Nicholas", 'Table For Two',
       'Tales of a Fourth Grade Nothing',
       'Taltos: Lives of the Mayfair Witches', 'Tara Road',
       'Tears of the Giraffe (No.1 Ladies Detective Agency)',
       'Tears of the Moon (Irish Trilogy)', 'Tell Me Lies (Tell Me Lies)',
       'Tell Me Your Dreams', 'Tell No One', 'Temptation',
       'That Camden Summer', 'The Accidental Tourist',
       'The Alchemist: A Fable About Following Your Dream', 'The Alibi',
       'The Alienist', 'The Amazing Adventures of Kavalier &amp; Clay',
       'The Amber Spyglass (His Dark Materials, Book 3)',
       'The Andromeda Strain', 'The Angel of Darkness', 'The Apprentice',
       'The Bachelor (Warner Books Contemporary Romance)',
       'The Bad Beginning (A Series of Unfortunate Events, Book 1)',
       'The Bad Place', 'The Beach House', 'The Bean Trees',
       'The Blind Assassin', 'The Blue Nowhere : A Novel',
       'The Bluest Eye', 'The Body Farm', "The Bonesetter's Daughter",
       'The Bonfire of the Vanities',
       "The Book of Ruth (Oprah's Book Club (Paperback))",
       'The Bourne Identity', 'The Bourne Supremacy',
       'The Bourne Ultimatum', 'The Boy Next Door', 'The Brethren',
       'The Bridges of Madison County', 'The Burden of Proof',
       'The Cardinal of the Kremlin (Jack Ryan Novels)', 'The Carousel',
       'The Catcher in the Rye',
       'The Celestine Prophecy (Celestine Prophecy)', 'The Chamber',
       'The Cider House Rules',
       "The Clan of the Cave Bear (Earth's Children (Paperback))",
       'The Client', 'The Clinic (Alex Delaware Novels (Paperback))',
       'The Color Purple',
       "The Color of Water: A Black Man's Tribute to His White Mother",
       'The Copper Beech', 'The Cradle Will Fall',
       'The Crimson Petal and the White', 'The Da Vinci Code',
       'The Dark Half', 'The Dead Zone', 'The Deep End of the Ocean',
       'The Devil Wears Prada : A Novel',
       'The Diary of Ellen Rimbauer: My Life at Rose Red',
       'The Divine Secrets of the Ya-Ya Sisterhood: A Novel',
       'The Dogs of Babel (Today Show Book Club #12)',
       'The Door to December',
       'The Drawing of the Three (The Dark Tower, Book 2)', 'The Edge',
       'The Eight', 'The Empty Chair', 'The English Patient',
       'The Eyre Affair: A Novel', 'The Face of Deception',
       'The Fellowship of the Ring (The Lord of the Rings, Part 1)',
       'The Firm', 'The First Counsel',
       'The First Wives Club Movie Tie In',
       'The Five People You Meet in Heaven', 'The Fourth Hand',
       "The General's Daughter", 'The Genesis Code', 'The Ghost',
       'The Gift', 'The Girl Who Loved Tom Gordon',
       "The Girls' Guide to Hunting and Fishing",
       'The Giver (21st Century Reference)', 'The Glass Lake',
       'The God of Small Things',
       'The Golden Compass (His Dark Materials, Book 1)',
       'The Great Gatsby', 'The Green Mile', 'The Grilling Season',
       'The Guardian', 'The Gunslinger (The Dark Tower, Book 1)',
       "The Handmaid's Tale", "The Hitchhiker's Guide to the Galaxy",
       'The Hobbit : The Enchanting Prelude to The Lord of the Rings',
       'The Honk and Holler Opening Soon', 'The Horse Whisperer',
       'The Hot Zone', 'The Hours : A Novel', 'The Hours: A Novel',
       'The House of the Spirits', 'The Hundred Secret Senses',
       'The Hunt for Red October',
       "The Idiot Girls' Action Adventure Club", 'The Jester',
       'The Joy Luck Club',
       'The Killing Game: Only One Can Win...and the Loser Dies',
       'The King of Torts', 'The Kiss', "The Kitchen God's Wife",
       'The Last Precinct', 'The Last Time They Met : A Novel',
       'The Little Friend', 'The Little Prince', 'The Long Road Home',
       'The Loop',
       "The Lost Boy: A Foster Child's Search for the Love of a Family",
       'The Lost World', 'The Lottery Winner : Alvirah And Willy Stories',
       'The Lovely Bones: A Novel', 'The Mists of Avalon',
       'The Most Wanted', 'The Mulberry Tree',
       'The Mummy or Ramses the Damned', 'The Murder Book',
       'The Nanny Diaries: A Novel', 'The Next Accident',
       "The No. 1 Ladies' Detective Agency (Today Show Book Club #8)",
       'The Notebook', 'The Other Boleyn Girl', 'The Partner',
       'The Pelican Brief',
       'The Perfect Storm : A True Story of Men Against the Sea',
       'The Phantom Tollbooth', 'The Pillars of the Earth',
       "The Pilot's Wife : A Novel",
       "The Plains of Passage (Earth's Children (Paperback))",
       'The Poisonwood Bible', 'The Poisonwood Bible: A Novel',
       'The Prince of Tides',
       "The Princess Bride: S Morgenstern's Classic Tale of True Love and High Adventure",
       'The Promise', 'The Pull of the Moon',
       'The Queen of the Damned (Vampire Chronicles (Paperback))',
       'The Rainmaker', 'The Rapture of Canaan', 'The Reader',
       'The Red Tent (Bestselling Backlist)', 'The Reef',
       'The Regulators',
       'The Reptile Room (A Series of Unfortunate Events, Book 2)',

In [346]:
book_list.to_csv('book_name.csv')

In [343]:
pickle.dump(book_list,open('book_list.pkl','wb'))

In [347]:
book_pivot.to_csv("book_pivot.csv")

In [764]:

def suggest1(book_name):
    l=[]
    book_index=np.where(book_pivot.index==book_name)[0][0]
    distances,suggestion=model.kneighbors(book_pivot.iloc[book_index,:].values.reshape(1, -1),n_neighbors=6)
    for i in range(len(suggestion)):
        l.append(book_pivot.index[suggestion[i]].values[1:6])
    return l

In [765]:
suggest1('1984')

[array(['No Safe Place', 'A Civil Action', "Foucault's Pendulum",
        'Long After Midnight', 'Abduction'], dtype=object)]

In [375]:
l

[array(['Exclusive', 'No Safe Place', 'Jacob Have I Loved',
        'Long After Midnight', 'The Cradle Will Fall'], dtype=object)]

In [377]:
for i in l[0]:
    print(i)

Exclusive
No Safe Place
Jacob Have I Loved
Long After Midnight
The Cradle Will Fall

In [378]:
l[0][0]

'Exclusive'

In [380]:
list(book_sparse)

[<1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 28 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 47 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 34 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 13 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 25 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 26 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 15 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 25 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 5 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 11 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 11 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 7 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 11 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 11 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 16 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 34 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 14 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 15 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 11 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 23 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 54 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 10 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 31 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 9 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 12 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 54 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 11 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 29 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 12 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 23 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 34 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 15 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 29 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 6 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 23 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 8 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 12 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 17 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 21 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 8 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 24 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 12 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 28 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 22 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 8 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 24 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 22 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 8 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 20 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 30 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 11 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 54 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 19 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 12 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 26 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 26 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 23 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 30 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 14 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 27 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 19 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 21 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 13 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 36 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 23 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 16 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 36 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 21 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 5 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 14 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 12 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 36 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 21 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 17 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 15 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 23 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 29 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 14 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 9 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 16 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 11 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 27 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 17 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 19 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 21 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 13 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 12 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 21 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 19 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 13 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 21 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 14 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 18 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 13 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 14 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 84 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 22 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 14 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 25 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 4 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 14 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 12 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 21 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 25 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 14 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 11 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 23 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 11 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 22 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 17 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 23 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 23 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 27 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 9 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 19 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 19 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 9 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 19 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 10 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 13 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 24 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 22 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 6 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 9 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 42 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 24 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 25 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 11 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 9 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 21 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 18 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 29 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 10 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 27 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 9 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 25 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 24 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 14 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 22 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 14 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 25 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 10 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 13 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 11 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 13 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 14 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 14 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 11 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 14 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 7 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 13 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 5 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 9 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 17 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 24 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 10 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 16 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 12 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 18 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 52 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 29 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 15 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 23 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 15 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 7 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 25 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 10 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 42 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 10 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 16 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 17 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'
 	with 25 stored elements in Compressed Sparse Row format>,
 <1x888 sparse matrix of type '<class 'numpy.float64'>'

In [381]:
help(csr_matrix)

Help on class csr_matrix in module scipy.sparse.csr:

class csr_matrix(scipy.sparse.compressed._cs_matrix)
 |  csr_matrix(arg1, shape=None, dtype=None, copy=False)
 |
 |  Compressed Sparse Row matrix
 |
 |  This can be instantiated in several ways:
 |      csr_matrix(D)
 |          with a dense matrix or rank-2 ndarray D
 |
 |      csr_matrix(S)
 |          with another sparse matrix S (equivalent to S.tocsr())
 |
 |      csr_matrix((M, N), [dtype])
 |          to construct an empty matrix with shape (M, N)
 |          dtype is optional, defaulting to dtype='d'.
 |
 |      csr_matrix((data, (row_ind, col_ind)), [shape=(M, N)])
 |          where ``data``, ``row_ind`` and ``col_ind`` satisfy the
 |          relationship ``a[row_ind[k], col_ind[k]] = data[k]``.
 |
 |      csr_matrix((data, indices, indptr), [shape=(M, N)])
 |          is the standard CSR representation where the column indices for
 |          row i are stored in ``indices[indptr[i]:indptr[i+1]]`` and their
 |          corresponding values are stored in ``data[indptr[i]:indptr[i+1]]``.
 |          If the shape parameter is not supplied, the matrix dimensions
 |          are inferred from the index arrays.
 |
 |  Attributes
 |  ----------
 |  dtype : dtype
 |      Data type of the matrix
 |  shape : 2-tuple
 |      Shape of the matrix
 |  ndim : int
 |      Number of dimensions (this is always 2)
 |  nnz
 |      Number of stored values, including explicit zeros
 |  data
 |      CSR format data array of the matrix
 |  indices
 |      CSR format index array of the matrix
 |  indptr
 |      CSR format index pointer array of the matrix
 |  has_sorted_indices
 |      Whether indices are sorted
 |
 |  Notes
 |  -----
 |
 |  Sparse matrices can be used in arithmetic operations: they support
 |  addition, subtraction, multiplication, division, and matrix power.
 |
 |  Advantages of the CSR format
 |    - efficient arithmetic operations CSR + CSR, CSR * CSR, etc.
 |    - efficient row slicing
 |    - fast matrix vector products
 |
 |  Disadvantages of the CSR format
 |    - slow column slicing operations (consider CSC)
 |    - changes to the sparsity structure are expensive (consider LIL or DOK)
 |
 |  Examples
 |  --------
 |
 |  >>> import numpy as np
 |  >>> from scipy.sparse import csr_matrix
 |  >>> csr_matrix((3, 4), dtype=np.int8).toarray()
 |  array([[0, 0, 0, 0],
 |         [0, 0, 0, 0],
 |         [0, 0, 0, 0]], dtype=int8)
 |
 |  >>> row = np.array([0, 0, 1, 2, 2, 2])
 |  >>> col = np.array([0, 2, 2, 0, 1, 2])
 |  >>> data = np.array([1, 2, 3, 4, 5, 6])
 |  >>> csr_matrix((data, (row, col)), shape=(3, 3)).toarray()
 |  array([[1, 0, 2],
 |         [0, 0, 3],
 |         [4, 5, 6]])
 |
 |  >>> indptr = np.array([0, 2, 3, 6])
 |  >>> indices = np.array([0, 2, 2, 0, 1, 2])
 |  >>> data = np.array([1, 2, 3, 4, 5, 6])
 |  >>> csr_matrix((data, indices, indptr), shape=(3, 3)).toarray()
 |  array([[1, 0, 2],
 |         [0, 0, 3],
 |         [4, 5, 6]])
 |
 |  Duplicate entries are summed together:
 |
 |  >>> row = np.array([0, 1, 2, 0])
 |  >>> col = np.array([0, 1, 1, 0])
 |  >>> data = np.array([1, 2, 4, 8])
 |  >>> csr_matrix((data, (row, col)), shape=(3, 3)).toarray()
 |  array([[9, 0, 0],
 |         [0, 2, 0],
 |         [0, 4, 0]])
 |
 |  As an example of how to construct a CSR matrix incrementally,
 |  the following snippet builds a term-document matrix from texts:
 |
 |  >>> docs = [["hello", "world", "hello"], ["goodbye", "cruel", "world"]]
 |  >>> indptr = [0]
 |  >>> indices = []
 |  >>> data = []
 |  >>> vocabulary = {}
 |  >>> for d in docs:
 |  ...     for term in d:
 |  ...         index = vocabulary.setdefault(term, len(vocabulary))
 |  ...         indices.append(index)
 |  ...         data.append(1)
 |  ...     indptr.append(len(indices))
 |  ...
 |  >>> csr_matrix((data, indices, indptr), dtype=int).toarray()
 |  array([[2, 1, 0, 0],
 |         [0, 1, 1, 1]])
 |
 |  Method resolution order:
 |      csr_matrix
 |      scipy.sparse.compressed._cs_matrix
 |      scipy.sparse.data._data_matrix
 |      scipy.sparse.base.spmatrix
 |      scipy.sparse.data._minmax_mixin
 |      scipy.sparse._index.IndexMixin
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __iter__(self)
 |
 |  getcol(self, i)
 |      Returns a copy of column i of the matrix, as a (m x 1)
 |      CSR matrix (column vector).
 |
 |  getrow(self, i)
 |      Returns a copy of row i of the matrix, as a (1 x n)
 |      CSR matrix (row vector).
 |
 |  tobsr(self, blocksize=None, copy=True)
 |      Convert this matrix to Block Sparse Row format.
 |
 |      With copy=False, the data/indices may be shared between this matrix and
 |      the resultant bsr_matrix.
 |
 |      When blocksize=(R, C) is provided, it will be used for construction of
 |      the bsr_matrix.
 |
 |  tocsc(self, copy=False)
 |      Convert this matrix to Compressed Sparse Column format.
 |
 |      With copy=False, the data/indices may be shared between this matrix and
 |      the resultant csc_matrix.
 |
 |  tocsr(self, copy=False)
 |      Convert this matrix to Compressed Sparse Row format.
 |
 |      With copy=False, the data/indices may be shared between this matrix and
 |      the resultant csr_matrix.
 |
 |  tolil(self, copy=False)
 |      Convert this matrix to List of Lists format.
 |
 |      With copy=False, the data/indices may be shared between this matrix and
 |      the resultant lil_matrix.
 |
 |  transpose(self, axes=None, copy=False)
 |      Reverses the dimensions of the sparse matrix.
 |
 |      Parameters
 |      ----------
 |      axes : None, optional
 |          This argument is in the signature *solely* for NumPy
 |          compatibility reasons. Do not pass in anything except
 |          for the default value.
 |      copy : bool, optional
 |          Indicates whether or not attributes of `self` should be
 |          copied whenever possible. The degree to which attributes
 |          are copied varies depending on the type of sparse matrix
 |          being used.
 |
 |      Returns
 |      -------
 |      p : `self` with the dimensions reversed.
 |
 |      See Also
 |      --------
 |      numpy.matrix.transpose : NumPy's implementation of 'transpose'
 |                               for matrices
 |
 |  ----------------------------------------------------------------------
 |  Data and other attributes defined here:
 |
 |  __slotnames__ = []
 |
 |  format = 'csr'
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from scipy.sparse.compressed._cs_matrix:
 |
 |  __eq__(self, other)
 |      Return self==value.
 |
 |  __ge__(self, other)
 |      Return self>=value.
 |
 |  __gt__(self, other)
 |      Return self>value.
 |
 |  __init__(self, arg1, shape=None, dtype=None, copy=False)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  __le__(self, other)
 |      Return self<=value.
 |
 |  __lt__(self, other)
 |      Return self<value.
 |
 |  __ne__(self, other)
 |      Return self!=value.
 |
 |  check_format(self, full_check=True)
 |      check whether the matrix format is valid
 |
 |      Parameters
 |      ----------
 |      full_check : bool, optional
 |          If `True`, rigorous check, O(N) operations. Otherwise
 |          basic check, O(1) operations (default True).
 |
 |  diagonal(self, k=0)
 |      Returns the kth diagonal of the matrix.
 |
 |      Parameters
 |      ----------
 |      k : int, optional
 |          Which diagonal to get, corresponding to elements a[i, i+k].
 |          Default: 0 (the main diagonal).
 |
 |          .. versionadded:: 1.0
 |
 |      See also
 |      --------
 |      numpy.diagonal : Equivalent numpy function.
 |
 |      Examples
 |      --------
 |      >>> from scipy.sparse import csr_matrix
 |      >>> A = csr_matrix([[1, 2, 0], [0, 0, 3], [4, 0, 5]])
 |      >>> A.diagonal()
 |      array([1, 0, 5])
 |      >>> A.diagonal(k=1)
 |      array([2, 3])
 |
 |  eliminate_zeros(self)
 |      Remove zero entries from the matrix
 |
 |      This is an *in place* operation.
 |
 |  getnnz(self, axis=None)
 |      Number of stored values, including explicit zeros.
 |
 |      Parameters
 |      ----------
 |      axis : None, 0, or 1
 |          Select between the number of values across the whole matrix, in
 |          each column, or in each row.
 |
 |      See also
 |      --------
 |      count_nonzero : Number of non-zero entries
 |
 |  maximum(self, other)
 |      Element-wise maximum between this and another matrix.
 |
 |  minimum(self, other)
 |      Element-wise minimum between this and another matrix.
 |
 |  multiply(self, other)
 |      Point-wise multiplication by another matrix, vector, or
 |      scalar.
 |
 |  prune(self)
 |      Remove empty space after all non-zero elements.
 |
 |  resize(self, *shape)
 |      Resize the matrix in-place to dimensions given by ``shape``
 |
 |      Any elements that lie within the new shape will remain at the same
 |      indices, while non-zero elements lying outside the new shape are
 |      removed.
 |
 |      Parameters
 |      ----------
 |      shape : (int, int)
 |          number of rows and columns in the new matrix
 |
 |      Notes
 |      -----
 |      The semantics are not identical to `numpy.ndarray.resize` or
 |      `numpy.resize`. Here, the same data will be maintained at each index
 |      before and after reshape, if that index is within the new bounds. In
 |      numpy, resizing maintains contiguity of the array, moving elements
 |      around in the logical matrix but not within a flattened representation.
 |
 |      We give no guarantees about whether the underlying data attributes
 |      (arrays, etc.) will be modified in place or replaced with new objects.
 |
 |  sort_indices(self)
 |      Sort the indices of this matrix *in place*
 |
 |  sorted_indices(self)
 |      Return a copy of this matrix with sorted indices
 |
 |  sum(self, axis=None, dtype=None, out=None)
 |      Sum the matrix elements over a given axis.
 |
 |      Parameters
 |      ----------
 |      axis : {-2, -1, 0, 1, None} optional
 |          Axis along which the sum is computed. The default is to
 |          compute the sum of all the matrix elements, returning a scalar
 |          (i.e., `axis` = `None`).
 |      dtype : dtype, optional
 |          The type of the returned matrix and of the accumulator in which
 |          the elements are summed.  The dtype of `a` is used by default
 |          unless `a` has an integer dtype of less precision than the default
 |          platform integer.  In that case, if `a` is signed then the platform
 |          integer is used while if `a` is unsigned then an unsigned integer
 |          of the same precision as the platform integer is used.
 |
 |          .. versionadded:: 0.18.0
 |
 |      out : np.matrix, optional
 |          Alternative output matrix in which to place the result. It must
 |          have the same shape as the expected output, but the type of the
 |          output values will be cast if necessary.
 |
 |          .. versionadded:: 0.18.0
 |
 |      Returns
 |      -------
 |      sum_along_axis : np.matrix
 |          A matrix with the same shape as `self`, with the specified
 |          axis removed.
 |
 |      See Also
 |      --------
 |      numpy.matrix.sum : NumPy's implementation of 'sum' for matrices
 |
 |  sum_duplicates(self)
 |      Eliminate duplicate matrix entries by adding them together
 |
 |      This is an *in place* operation.
 |
 |  toarray(self, order=None, out=None)
 |      Return a dense ndarray representation of this matrix.
 |
 |      Parameters
 |      ----------
 |      order : {'C', 'F'}, optional
 |          Whether to store multidimensional data in C (row-major)
 |          or Fortran (column-major) order in memory. The default
 |          is 'None', indicating the NumPy default of C-ordered.
 |          Cannot be specified in conjunction with the `out`
 |          argument.
 |
 |      out : ndarray, 2-D, optional
 |          If specified, uses this array as the output buffer
 |          instead of allocating a new array to return. The provided
 |          array must have the same shape and dtype as the sparse
 |          matrix on which you are calling the method. For most
 |          sparse types, `out` is required to be memory contiguous
 |          (either C or Fortran ordered).
 |
 |      Returns
 |      -------
 |      arr : ndarray, 2-D
 |          An array with the same shape and containing the same
 |          data represented by the sparse matrix, with the requested
 |          memory order. If `out` was passed, the same object is
 |          returned after being modified in-place to contain the
 |          appropriate values.
 |
 |  tocoo(self, copy=True)
 |      Convert this matrix to COOrdinate format.
 |
 |      With copy=False, the data/indices may be shared between this matrix and
 |      the resultant coo_matrix.
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors inherited from scipy.sparse.compressed._cs_matrix:
 |
 |  has_canonical_format
 |      Determine whether the matrix has sorted indices and no duplicates
 |
 |      Returns
 |          - True: if the above applies
 |          - False: otherwise
 |
 |      has_canonical_format implies has_sorted_indices, so if the latter flag
 |      is False, so will the former be; if the former is found True, the
 |      latter flag is also set.
 |
 |  has_sorted_indices
 |      Determine whether the matrix has sorted indices
 |
 |      Returns
 |          - True: if the indices of the matrix are in sorted order
 |          - False: otherwise
 |
 |  ----------------------------------------------------------------------
 |  Data and other attributes inherited from scipy.sparse.compressed._cs_matrix:
 |
 |  __hash__ = None
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from scipy.sparse.data._data_matrix:
 |
 |  __abs__(self)
 |
 |  __imul__(self, other)
 |
 |  __itruediv__(self, other)
 |
 |  __neg__(self)
 |
 |  __round__(self, ndigits=0)
 |
 |  arcsin(self)
 |      Element-wise arcsin.
 |
 |      See `numpy.arcsin` for more information.
 |
 |  arcsinh(self)
 |      Element-wise arcsinh.
 |
 |      See `numpy.arcsinh` for more information.
 |
 |  arctan(self)
 |      Element-wise arctan.
 |
 |      See `numpy.arctan` for more information.
 |
 |  arctanh(self)
 |      Element-wise arctanh.
 |
 |      See `numpy.arctanh` for more information.
 |
 |  astype(self, dtype, casting='unsafe', copy=True)
 |      Cast the matrix elements to a specified type.
 |
 |      Parameters
 |      ----------
 |      dtype : string or numpy dtype
 |          Typecode or data-type to which to cast the data.
 |      casting : {'no', 'equiv', 'safe', 'same_kind', 'unsafe'}, optional
 |          Controls what kind of data casting may occur.
 |          Defaults to 'unsafe' for backwards compatibility.
 |          'no' means the data types should not be cast at all.
 |          'equiv' means only byte-order changes are allowed.
 |          'safe' means only casts which can preserve values are allowed.
 |          'same_kind' means only safe casts or casts within a kind,
 |          like float64 to float32, are allowed.
 |          'unsafe' means any data conversions may be done.
 |      copy : bool, optional
 |          If `copy` is `False`, the result might share some memory with this
 |          matrix. If `copy` is `True`, it is guaranteed that the result and
 |          this matrix do not share any memory.
 |
 |  ceil(self)
 |      Element-wise ceil.
 |
 |      See `numpy.ceil` for more information.
 |
 |  conj(self, copy=True)
 |      Element-wise complex conjugation.
 |
 |      If the matrix is of non-complex data type and `copy` is False,
 |      this method does nothing and the data is not copied.
 |
 |      Parameters
 |      ----------
 |      copy : bool, optional
 |          If True, the result is guaranteed to not share data with self.
 |
 |      Returns
 |      -------
 |      A : The element-wise complex conjugate.
 |
 |  copy(self)
 |      Returns a copy of this matrix.
 |
 |      No data/indices will be shared between the returned value and current
 |      matrix.
 |
 |  count_nonzero(self)
 |      Number of non-zero entries, equivalent to
 |
 |      np.count_nonzero(a.toarray())
 |
 |      Unlike getnnz() and the nnz property, which return the number of stored
 |      entries (the length of the data attribute), this method counts the
 |      actual number of non-zero entries in data.
 |
 |  deg2rad(self)
 |      Element-wise deg2rad.
 |
 |      See `numpy.deg2rad` for more information.
 |
 |  expm1(self)
 |      Element-wise expm1.
 |
 |      See `numpy.expm1` for more information.
 |
 |  floor(self)
 |      Element-wise floor.
 |
 |      See `numpy.floor` for more information.
 |
 |  log1p(self)
 |      Element-wise log1p.
 |
 |      See `numpy.log1p` for more information.
 |
 |  power(self, n, dtype=None)
 |      This function performs element-wise power.
 |
 |      Parameters
 |      ----------
 |      n : n is a scalar
 |
 |      dtype : If dtype is not specified, the current dtype will be preserved.
 |
 |  rad2deg(self)
 |      Element-wise rad2deg.
 |
 |      See `numpy.rad2deg` for more information.
 |
 |  rint(self)
 |      Element-wise rint.
 |
 |      See `numpy.rint` for more information.
 |
 |  sign(self)
 |      Element-wise sign.
 |
 |      See `numpy.sign` for more information.
 |
 |  sin(self)
 |      Element-wise sin.
 |
 |      See `numpy.sin` for more information.
 |
 |  sinh(self)
 |      Element-wise sinh.
 |
 |      See `numpy.sinh` for more information.
 |
 |  sqrt(self)
 |      Element-wise sqrt.
 |
 |      See `numpy.sqrt` for more information.
 |
 |  tan(self)
 |      Element-wise tan.
 |
 |      See `numpy.tan` for more information.
 |
 |  tanh(self)
 |      Element-wise tanh.
 |
 |      See `numpy.tanh` for more information.
 |
 |  trunc(self)
 |      Element-wise trunc.
 |
 |      See `numpy.trunc` for more information.
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors inherited from scipy.sparse.data._data_matrix:
 |
 |  dtype
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from scipy.sparse.base.spmatrix:
 |
 |  __add__(self, other)
 |
 |  __bool__(self)
 |
 |  __div__(self, other)
 |
 |  __getattr__(self, attr)
 |
 |  __iadd__(self, other)
 |
 |  __idiv__(self, other)
 |
 |  __isub__(self, other)
 |
 |  __len__(self)
 |      # What should len(sparse) return? For consistency with dense matrices,
 |      # perhaps it should be the number of rows?  But for some uses the number of
 |      # non-zeros is more important.  For now, raise an exception!
 |
 |  __matmul__(self, other)
 |
 |  __mul__(self, other)
 |      interpret other and call one of the following
 |
 |      self._mul_scalar()
 |      self._mul_vector()
 |      self._mul_multivector()
 |      self._mul_sparse_matrix()
 |
 |  __nonzero__ = __bool__(self)
 |
 |  __pow__(self, other)
 |
 |  __radd__(self, other)
 |
 |  __rdiv__(self, other)
 |
 |  __repr__(self)
 |      Return repr(self).
 |
 |  __rmatmul__(self, other)
 |
 |  __rmul__(self, other)
 |
 |  __rsub__(self, other)
 |
 |  __rtruediv__(self, other)
 |
 |  __str__(self)
 |      Return str(self).
 |
 |  __sub__(self, other)
 |
 |  __truediv__(self, other)
 |
 |  asformat(self, format, copy=False)
 |      Return this matrix in the passed format.
 |
 |      Parameters
 |      ----------
 |      format : {str, None}
 |          The desired matrix format ("csr", "csc", "lil", "dok", "array", ...)
 |          or None for no conversion.
 |      copy : bool, optional
 |          If True, the result is guaranteed to not share data with self.
 |
 |      Returns
 |      -------
 |      A : This matrix in the passed format.
 |
 |  asfptype(self)

In [393]:
l=book_sparse.toarray().reshape(1,-1)
l

array([[9., 0., 0., ..., 0., 0., 0.]])

In [394]:
pickle.dump(l,open('book_sparse.pkl','wb'))

In [387]:
book_sparse.to_csv('book_sparse.csv')

AttributeError: to_csv not found

In [411]:
book_pivot

user_id,254,2276,2766,2977,3363,3757,4017,4385,6242,6251,...,274004,274061,274301,274308,274808,275970,277427,277478,277639,278418
title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
84 Charing Cross Road,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,7.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
You Belong To Me,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [416]:
pickle.dump(book_pivot,open('book_pivot.pkl','wb'))

In [406]:
ss=open('book_pivot.pkl','rb')

In [408]:
ss=pd.read_pickle('book_pivot.pkl')

In [409]:
ss

                                                 title
0                                                 1984
1                                  1st to Die: A Novel
2                                           2nd Chance
3                                            4 Blondes
4                                84 Charing Cross Road
..                                                 ...
737                                    Year of Wonders
738                                   You Belong To Me
739  Zen and the Art of Motorcycle Maintenance: An ...
740                                               Zoya
741                                \O\" Is for Outlaw"

[742 rows x 1 columns]

In [417]:
ss=pickle.load(open('book_pivot.pkl','rb'))

In [418]:
ss

user_id,254,2276,2766,2977,3363,3757,4017,4385,6242,6251,...,274004,274061,274301,274308,274808,275970,277427,277478,277639,278418
title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
84 Charing Cross Road,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,7.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
You Belong To Me,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [419]:
pickle.dump(book_sparse,open('book_sparse.pkl','wb'))

In [420]:
ss=pickle.load(open('book_sparse.pkl','rb'))

In [424]:
ss

<742x888 sparse matrix of type '<class 'numpy.float64'>'
	with 14942 stored elements in Compressed Sparse Row format>

In [425]:
book_sparse

<742x888 sparse matrix of type '<class 'numpy.float64'>'
	with 14942 stored elements in Compressed Sparse Row format>

In [432]:
book_list.head(2)

                 title
0                 1984
1  1st to Die: A Novel

In [431]:
image.head(2)

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...

In [460]:
image[image['Book-Title']=='1984'][0:1]

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
2104,0451524934,1984,George Orwell,1990,Signet Book,http://images.amazon.com/images/P/0451524934.0...,http://images.amazon.com/images/P/0451524934.0...,http://images.amazon.com/images/P/0451524934.0...

In [478]:
image['Image-URL-M'][image['Book-Title']=='1984'][0:1]

2104    http://images.amazon.com/images/P/0451524934.0...
Name: Image-URL-M, dtype: object

In [472]:
image['Image-URL-M'][0]

'http://images.amazon.com/images/P/0195153448.01.MZZZZZZZ.jpg'

In [461]:
image.shape

(271360, 8)

In [462]:
image=image[['ISBN','Book-Title','Image-URL-M']]
image.head(3)

,ISBN,Book-Title,Image-URL-M
0,0195153448,Classical Mythology,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,http://images.amazon.com/images/P/0060973129.0...

In [463]:
pickle.dump(image,open('book_image.pkl','wb'))

In [465]:
ll=pickle.load(open('book_image.pkl','rb'))
ll

,ISBN,Book-Title,Image-URL-M
0,0195153448,Classical Mythology,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,http://images.amazon.com/images/P/0393045218.0...
...,...,...,...
271355,0440400988,There's a Bat in Bunk Five,http://images.amazon.com/images/P/0440400988.0...
271356,0525447644,From One to One Hundred,http://images.amazon.com/images/P/0525447644.0...
271357,006008667X,Lily Dale : The True Story of the Town that Ta...,http://images.amazon.com/images/P/006008667X.0...
271358,0192126040,Republic (World's Classics),http://images.amazon.com/images/P/0192126040.0...
271359,0767409752,A Guided Tour of Rene Descartes' Meditations o...,http://images.amazon.com/images/P/0767409752.0...

In [601]:
ll['Image-URL-M'][0]

'http://images.amazon.com/images/P/0195153448.01.MZZZZZZZ.jpg'

In [482]:
image['ISBN'][image['Book-Title']=='1984'][0:1].values[0]

'0451524934'

In [483]:
image['ISBN'][image['Book-Title']=='1984'][0:1]

2104    0451524934
Name: ISBN, dtype: object

In [504]:
book_name=[i for i in book_list['title']]
ISBN=image[image['Book-Title'].isin([i for i in book_list['title']])]

In [511]:
ISBN.groupby('Book-Title')['Image-URL-M'].count().reset_index()

                                            Book-Title  Image-URL-M
0                                                 1984            9
1                                  1st to Die: A Novel            2
2                                           2nd Chance            4
3                                            4 Blondes            1
4                                84 Charing Cross Road            3
..                                                 ...          ...
737                                    Year of Wonders            1
738                                   You Belong To Me            1
739  Zen and the Art of Motorcycle Maintenance: An ...            3
740                                               Zoya            2
741                                \O\" Is for Outlaw"            2

[742 rows x 2 columns]

In [488]:
[i for i in book_list['title']]

['1984',
 '1st to Die: A Novel',
 '2nd Chance',
 '4 Blondes',
 '84 Charing Cross Road',
 'A Bend in the Road',
 'A Case of Need',
 'A Child Called \\It\\": One Child\'s Courage to Survive"',
 'A Civil Action',
 'A Cry In The Night',
 'A Darkness More Than Night',
 'A Day Late and a Dollar Short',
 'A Fine Balance',
 'A Great Deliverance',
 'A Heartbreaking Work of Staggering Genius',
 'A Is for Alibi (Kinsey Millhone Mysteries (Paperback))',
 'A Lesson Before Dying (Vintage Contemporaries (Paperback))',
 'A Man Named Dave: A Story of Triumph and Forgiveness',
 'A Man in Full',
 'A Map of the World',
 'A Painted House',
 'A Patchwork Planet',
 'A Prayer for Owen Meany',
 'A Thin Dark Line (Mysteries &amp; Horror)',
 "A Thousand Acres (Ballantine Reader's Circle)",
 'A Time to Kill',
 "A Virtuous Woman (Oprah's Book Club (Paperback))",
 'A Walk to Remember',
 'A Widow for One Year',
 'A Wrinkle In Time',
 'A Wrinkle in Time',
 'A Year in Provence',
 "ANGELA'S ASHES",
 'Abduction',
 'About a Boy',
 'Absolute Power',
 'Acceptable Risk',
 'Accident',
 'Airframe',
 'Alaska',
 'All Around the Town',
 'All Creatures Great and Small',
 'All I Really Need to Know',
 'All That Remains (Kay Scarpetta Mysteries (Paperback))',
 'All the Pretty Horses (The Border Trilogy, Vol 1)',
 'Along Came a Spider (Alex Cross Novels)',
 'American Gods',
 'And Then You Die',
 "Angela's Ashes (MMP) : A Memoir",
 "Angela's Ashes: A Memoir",
 'Angels',
 'Angels &amp; Demons',
 'Angus, Thongs and Full-Frontal Snogging: Confessions of Georgia Nicolson',
 'Animal Dreams',
 'Animal Farm',
 'Anne Frank: The Diary of a Young Girl',
 'Anne of Avonlea (Anne of Green Gables Novels (Paperback))',
 'Anne of Green Gables (Anne of Green Gables Novels (Paperback))',
 'Anne of the Island',
 'Artemis Fowl (Artemis Fowl, Book 1)',
 'Ashes to Ashes',
 'At Home in Mitford (The Mitford Years)',
 'Atonement : A Novel',
 'B Is for Burglar (Kinsey Millhone Mysteries (Paperback))',
 'Back Roads',
 'Bag of Bones',
 'Balzac and the Little Chinese Seamstress : A Novel',
 'Bastard Out of Carolina',
 'Beach House',
 'Beach Music',
 'Before I Say Good-Bye',
 'Bel Canto: A Novel',
 'Beloved',
 'Beloved (Plume Contemporary Fiction)',
 'Betrayal in Death',
 "Big Cherry Holler: A Big Stone Gap Novel (Ballantine Reader's Circle)",
 "Big Stone Gap: A Novel (Ballantine Reader's Circle)",
 'Big Trouble',
 'Billy Straight : A Novel',
 'Birthright',
 'Bittersweet',
 'Black House',
 'Black Notice',
 'Black and Blue',
 'Bleachers',
 'Blessings',
 'Blood Work',
 'Blue Diary',
 'Body of Evidence (Kay Scarpetta Mysteries (Paperback))',
 'Body of Lies',
 'Brave New World',
 'Breath, Eyes, Memory',
 'Breathing Lessons',
 'Bridge to Terabithia',
 'Bridget Jones : The Edge of Reason',
 "Bridget Jones's Diary",
 'Bridget Jones: The Edge of Reason',
 'By the Light of the Moon',
 'C Is for Corpse (Kinsey Millhone Mysteries (Paperback))',
 "CAT'S EYE",
 'Call of the Wild',
 'Carnal Innocence',
 'Carolina Moon',
 'Carrie',
 'Cat &amp; Mouse (Alex Cross Novels)',
 'Catering to Nobody',
 'Cause of Death',
 'Certain Prey',
 "Charlotte's Web (Trophy Newbery)",
 'Charming Billy',
 'Chicken Soup for the Soul (Chicken Soup for the Soul)',
 "Chicken Soup for the Woman's Soul (Chicken Soup for the Soul Series (Paper))",
 'Chocolat',
 'Choke',
 'Chosen Prey',
 'Christine',
 'Chromosome 6',
 'Circle of Friends',
 'Clear and Present Danger (Jack Ryan Novels)',
 'Cold Mountain',
 'Cold Mountain : A Novel',
 'Cold Sassy Tree',
 'Colony',
 'Coming Home',
 'Confessions of a Shopaholic (Summer Display Opportunity)',
 'Confessions of an Ugly Stepsister : A Novel',
 'Congo',
 'Contact',
 'Contagion',
 'Coraline',
 'Couplehood',
 'Cradle and All',
 'Crazy for You',
 'Cruel &amp; Unusual (Kay Scarpetta Mysteries (Paperback))',
 'Cry Wolf',
 'Cujo',
 'D Is for Deadbeat (Kinsey Millhone Mysteries (Paperback))',
 'Daddy',
 "Daddy's Little Girl",
 'Daisy Fay and the Miracle Man',
 'Dance upon the Air (Three Sisters Island Trilogy)',
 'Dances With Wolves',
 'Dangerous',
 'Dark Angel',
 'Dark Paradise',
 'Dark Rivers of the Heart',
 'Dawn (Cutler)',
 'Dead Run',
 'Death du Jour',
 'Debt of Honor (Jack Ryan Novels)',
 'Deception Point',
 'Deck the Halls (Holiday Classics)',
 'Degree of Guilt',
 'Deja Dead',
 'Desperation',
 'Devices and Desires',
 'Different Seasons',
 'Digital Fortress : A Thriller',
 'Disclosure',
 'Divine Secrets of the Ya-Ya Sisterhood: A Novel',
 'Dolores Claiborne',
 "Don't Stand Too Close to a Naked Man",
 "Don't Sweat the Small Stuff and It's All Small Stuff : Simple Ways to Keep the Little Things from Taking Over Your Life (Don't Sweat the Small Stuff Series)",
 "Dr. Atkins' New Diet Revolution",
 'Dragon Tears',
 'Dragonfly in Amber',
 'Dream Country',
 'Dreamcatcher',
 'Drowning Ruth',
 "Drowning Ruth (Oprah's Book Club)",
 'Drums of Autumn',
 "Dude, Where's My Country?",
 'Dust to Dust',
 'Dying for Chocolate (Culinary Mysteries (Paperback))',
 'E Is for Evidence: A Kinsey Millhone Mystery (Kinsey Millhone Mysteries (Paperback))',
 'Easy Prey',
 'Echoes',
 'Ellen Foster',
 'Empire Falls',
 "Ender's Game (Ender Wiggins Saga (Paperback))",
 'Engaging The Enemy',
 'Envy',
 'Evening Class',
 "Everything's Eventual : 14 Dark Tales",
 'Exclusive',
 'Executive Orders (Jack Ryan Novels)',
 'Eyes of Prey',
 'Eyes of a Child',
 'F Is for Fugitive (Kinsey Millhone Mysteries (Paperback))',
 'FORREST GUMP (Movie Tie in)',
 'Face the Fire (Three Sisters Island Trilogy)',
 'Fahrenheit 451',
 'Faking It',
 'Fall On Your Knees (Oprah #45)',
 'Falling Angels',
 'False Memory',
 'Family Album',
 'Fast Food Nation: The Dark Side of the All-American Meal',
 'Fast Women',
 'Fat Tuesday',
 'Fatal Cure',
 'Fatherhood',
 'Fear Nothing',
 'Final Target',
 'Fine Things',
 'Fingersmith',
 'Five Days in Paris',
 'Five Quarters of the Orange',
 'Flesh and Blood',
 'Forever... : A Novel of Good and Evil, Love and Hope',
 "Fortune's Rocks : A Novel",
 "Fortune's Rocks: A Novel",
 "Foucault's Pendulum",
 'Four Blind Mice',
 'Four Past Midnight',
 'Four To Score (A Stephanie Plum Novel)',
 'Fried Green Tomatoes at the Whistle Stop Cafe',
 "From Potter's Field",
 'From the Corner of His Eye',
 "Full House (Janet Evanovich's Full Series)",
 "Full Tilt (Janet Evanovich's Full Series)",
 'G Is for Gumshoe (Kinsey Millhone Mysteries (Paperback))',
 'GARDEN OF SHADOWS (Dollanger Saga (Paperback))',
 "Gerald's Game",
 'Girl in Hyacinth Blue',
 'Girl with a Pearl Earring',
 'Girl, Interrupted',
 'Good Omens',
 'Good in Bed',
 'Gorky Park',
 'Granny Dan',
 'Guardian Angel',
 'Guilty Pleasures (Anita Blake Vampire Hunter (Paperback))',
 'Guilty as Sin',
 'H Is for Homicide (Kinsey Millhone Mysteries (Paperback))',
 'Hannibal',
 'Hard Eight : A Stephanie Plum Novel (A Stephanie Plum Novel)',
 'Harry Potter and the Chamber of Secrets (Book 2)',
 'Harry Potter and the Goblet of Fire (Book 4)',
 'Harry Potter and the Order of the Phoenix (Book 5)',
 'Harry Potter and the Prisoner of Azkaban (Book 3)',
 "Harry Potter and the Sorcerer's Stone (Book 1)",
 "Harry Potter and the Sorcerer's Stone (Harry Potter (Paperback))",
 'Harvest',
 'Heart of the Sea (Irish Trilogy)',
 'Heartbeat',
 'Heartbreaker',
 'Hearts In Atlantis',
 'Hearts in Atlantis',
 'Heaven and Earth (Three Sisters Island Trilogy)',
 'Hemlock Bay',
 'Here on Earth',
 'Hide &amp; Seek',
 'Hideaway',
 'High Fidelity',
 'High Five (A Stephanie Plum Novel)',
 'Holes (Yearling Newbery)',
 'Homecoming',
 'Homeport',
 "Hornet's Nest",
 'Hot Six : A Stephanie Plum Novel (A Stephanie Plum Novel)',
 'House of Sand and Fog',
 'How Stella Got Her Groove Back',
 'How to Be Good',
 'How to Make an American Quilt',
 'I Capture the Castle',
 'I Is for Innocent',
 'I Know This Much Is True',
 "I Know This Much Is True (Oprah's Book Club)",
 'I Know Why the Caged Bird Sings',
 "I'll Be Seeing You",
 'Icebound',
 'Icy Sparks',
 'If Only It Were True',
 'If Tomorrow Comes',
 'Impulse',
 'In Her Shoes : A Novel',
 'Inner Harbor (Quinn Brothers (Paperback))',
 'Insomnia',
 'Intensity',
 'Interview with the Vampire',
 'Into Thin Air : A Personal Account of the Mt. Everest Disaster',
 'Into the Wild',
 'Invasion',
 'Irish Hearts',
 'Isle of Dogs',
 'It',
 'It Was on Fire When I Lay Down on It',
 "It's Always Something",
 'J Is for Judgment',
 'Jack &amp; Jill (Alex Cross Novels)',
 'Jacob Have I Loved',
 'Jemima J: A Novel About Ugly Ducklings and Swans',
 'Jewel',
 "Jewel (Oprah's Book Club)",
 'Jewels of the Sun (Irish Trilogy)',
 'Journey',
 'Jurassic Park',
 'K Is for Killer (Kinsey Millhone Mysteries (Paperback))',
 'Kaleidoscope',
 'Key of Knowledge (Key Trilogy (Paperback))',
 'Key of Light (Key Trilogy (Paperback))',
 'Key of Valor (Roberts, Nora. Key Trilogy, 3.)',
 'Killjoy',
 'Kiss the Girls',
 'L Is for Lawless',
 'Ladder of Years',
 'Lake Wobegon Days',
 'Lake Wobegon days',
 "Lamb : The Gospel According to Biff, Christ's Childhood Pal",
 'Last Chance Saloon',
 'Last Man Standing',
 "Left Behind: A Novel of the Earth's Last Days (Left Behind No. 1)",
 'Let Me Call You Sweetheart',
 'Life of Pi',
 'Lightning',
 'Like Water for Chocolate : A Novel in Monthly Installments with Recipes, Romances, and Home Remedies',
 'Like Water for Chocolate: A Novel in Monthly Installments With Recipes, Romances and Home Remedies',
 'Like Water for Chocolate: A Novel in Monthly Installments, With Recipes, Romances, and Home Remedies',
 'Little Altars Everywhere: A Novel',
 'Long After Midnight',
 'Lord of the Flies',
 'Love in the Time of Cholera (Penguin Great Books of the 20th Century)',
 'Loves Music, Loves to Dance',
 'Lucky : A Memoir',
 'Lucky Man: A Memoir',
 'M Is for Malice',
 'Macgregor Brides (Macgregors)',
 'Macgregor Grooms (Macgregors)',
 'Master of the Game',
 'Matilda',
 'Me Talk Pretty One Day',
 'Men Are from Mars, Women Are from Venus: A Practical Guide for Improving Communication and Getting What You Want in Your Relationships',
 'Mercy',
 'Message from Nam',
 'Message in a Bottle',
 'Middlesex: A Novel',
 'Midnight',
 'Midnight Bayou',
 'Midnight in the Garden of Good and Evil',
 'Midnight in the Garden of Good and Evil: A Savannah Story',
 'Midwives: A Novel',
 'Mind Prey',
 'Mirror Image',
 'Misery',
 'Miss Julia Speaks Her Mind : A Novel',
 'Monster : A Novel (Alex Delaware Novels (Paperback))',
 'Montana Sky',
 'Moo',
 'Moonlight Becomes You',
 'Morality for Beautiful Girls (No.1 Ladies Detective Agency)',
 'Mortal Fear',
 'Mortal Prey',
 'Mother of Pearl',
 'Mr. Murder',
 'My Gal Sunday',
 'Mystic River',
 'N Is for Noose',
 'Naked',
 'Needful Things',
 'Nerd in Shining Armor',
 'Neuromancer (Remembering Tomorrow)',
 'Neverwhere',
 'Nickel and Dimed: On (Not) Getting By in America',
 'Nicolae: The Rise of Antichrist (Left Behind No. 3)',
 'Night',
 'Night Prey',
 'Night Sins',
 'Night Whispers',
 'Nightmares &amp; Dreamscapes',
 'Nights in Rodanthe',
 'No Greater Love',
 'No Safe Place',
 'Notes from a Small Island',
 'Nothing Lasts Forever',
 'Now You See Her',
 'On the Street Where You Live',
 'One Door Away from Heaven',
 'One True Thing',
 'One for the Money (A Stephanie Plum Novel)',
 'One for the Money (Stephanie Plum Novels (Paperback))',
 'Oryx and Crake',
 'Outlander',
 'Over the Edge',
 'P Is for Peril',
 'Paradise',
 'Patriot Games (Jack Ryan Novels)',
 'Pay It Forward',
 'Peace Like a River',
 'Pet Sematary',
 'Phantoms',
 'Pigs in Heaven',
 'Plainsong (Vintage Contemporaries)',
 'Pleading Guilty',
 'Plum Island',
 'Point of Origin',
 'Politically Correct Bedtime Stories: Modern Tales for Our Life and Times',
 'Pop Goes the Weasel',
 'Portrait in Death',
 'Possession : A Romance',
 'Postmortem',
 'Practical Magic',
 'Presumed Innocent',
 "Pretend You Don't See Her",
 'Pride and Prejudice',
 'Primary Colors: A Novel of Politics',
 'Prime Cut',
 'Prodigal Summer',
 'Prodigal Summer: A Novel',
 'Purity in Death',
 'Q Is for Quarry',
 'Quentins',
 'Rainbow Six',
 'Range of Motion',
 'Reap the Wind',
 'Rebecca',
 'Red Dragon',
 'Red Storm Rising',
 'Remember Me',
 'Riptide',
 'Rising Sun',
 'Rising Tides',
 "River's End",
 'River, Cross My Heart',
 'Rose Madder',
 'Roses Are Red (Alex Cross Novels)',
 'Rules of Prey',
 'SHIPPING NEWS',
 'STONES FROM THE RIVER',
 'Sacred Sins',
 'Saint Maybe',
 'Sanctuary',
 'Saving Faith',
 'Scarlet Feather',
 'Scarlett : The Sequel to Margaret Mitchell\'s \\Gone With the Wind\\""',
 "Schindler's List",
 'Sea Glass: A Novel',
 'Sea Swept (Quinn Brothers (Paperback))',
 'Seabiscuit',
 'Seabiscuit: An American Legend',
 'Second Nature',
 'Secret History',
 'Secrets',
 'Seize the Night',
 'September',
 'Seven Habits Of Highly Effective People',
 'Seven Up (A Stephanie Plum Novel)',
 'Shadow Prey',
 'Shadowfires',
 'Shattered',
 "She's Come Undone (Oprah's Book Club (Paperback))",
 "She's Come Undone (Oprah's Book Club)",
 'Shell Seekers',
 'Shopaholic Takes Manhattan (Summer Display Opportunity)',
 'Shopaholic Ties the Knot',
 'Sick Puppy',
 'Silence of the Lambs',
 'Silent Witness',
 'Sisterhood of the Traveling Pants',
 'Skeleton Crew',
 'Skipping Christmas',
 'Slammerkin',
 "Slaughterhouse Five or the Children's Crusade: A Duty Dance With Death",
 'Sleepers',
 'Slow Waltz in Cedar Bend',
 'Small Town Girl',
 'Smart Women',
 "Smilla's Sense of Snow",
 'Snow Falling on Cedars',
 'Sole Survivor',
 "Song of Solomon (Oprah's Book Club (Paperback))",
 "Songs in Ordinary Time (Oprah's Book Club (Paperback))",
 "Sophie's World: A Novel About the History of Philosophy",
 'Southern Cross',
 'Sphere',
 'Standoff',
 'Stanislaski Brothers (Silhouette Promo)',
 'Still Waters',
 'Stillwatch',
 'Strangers',
 'Stupid White Men ...and Other Sorry Excuses for the State of the Nation!',
 'Sudden Prey',
 'Summer Pleasures',
 'Summer Sisters',
 "Suzanne's Diary for Nicholas",
 'Table For Two',
 'Tales of a Fourth Grade Nothing',
 'Taltos: Lives of the Mayfair Witches',
 'Tara Road',
 'Tears of the Giraffe (No.1 Ladies Detective Agency)',
 'Tears of the Moon (Irish Trilogy)',
 'Tell Me Lies (Tell Me Lies)',
 'Tell Me Your Dreams',
 'Tell No One',
 'Temptation',
 'That Camden Summer',
 'The Accidental Tourist',
 'The Alchemist: A Fable About Following Your Dream',
 'The Alibi',
 'The Alienist',
 'The Amazing Adventures of Kavalier &amp; Clay',
 'The Amber Spyglass (His Dark Materials, Book 3)',
 'The Andromeda Strain',
 'The Angel of Darkness',
 'The Apprentice',
 'The Bachelor (Warner Books Contemporary Romance)',
 'The Bad Beginning (A Series of Unfortunate Events, Book 1)',
 'The Bad Place',
 'The Beach House',
 'The Bean Trees',
 'The Blind Assassin',
 'The Blue Nowhere : A Novel',
 'The Bluest Eye',
 'The Body Farm',
 "The Bonesetter's Daughter",
 'The Bonfire of the Vanities',
 "The Book of Ruth (Oprah's Book Club (Paperback))",
 'The Bourne Identity',
 'The Bourne Supremacy',
 'The Bourne Ultimatum',
 'The Boy Next Door',
 'The Brethren',
 'The Bridges of Madison County',
 'The Burden of Proof',
 'The Cardinal of the Kremlin (Jack Ryan Novels)',
 'The Carousel',
 'The Catcher in the Rye',
 'The Celestine Prophecy (Celestine Prophecy)',
 'The Chamber',
 'The Cider House Rules',
 "The Clan of the Cave Bear (Earth's Children (Paperback))",
 'The Client',
 'The Clinic (Alex Delaware Novels (Paperback))',
 'The Color Purple',
 "The Color of Water: A Black Man's Tribute to His White Mother",
 'The Copper Beech',
 'The Cradle Will Fall',
 'The Crimson Petal and the White',
 'The Da Vinci Code',
 'The Dark Half',
 'The Dead Zone',
 'The Deep End of the Ocean',
 'The Devil Wears Prada : A Novel',
 'The Diary of Ellen Rimbauer: My Life at Rose Red',
 'The Divine Secrets of the Ya-Ya Sisterhood: A Novel',
 'The Dogs of Babel (Today Show Book Club #12)',
 'The Door to December',
 'The Drawing of the Three (The Dark Tower, Book 2)',
 'The Edge',
 'The Eight',
 'The Empty Chair',
 'The English Patient',
 'The Eyre Affair: A Novel',
 'The Face of Deception',
 'The Fellowship of the Ring (The Lord of the Rings, Part 1)',
 'The Firm',
 'The First Counsel',
 'The First Wives Club Movie Tie In',
 'The Five People You Meet in Heaven',
 'The Fourth Hand',
 "The General's Daughter",
 'The Genesis Code',
 'The Ghost',
 'The Gift',
 'The Girl Who Loved Tom Gordon',
 "The Girls' Guide to Hunting and Fishing",
 'The Giver (21st Century Reference)',
 'The Glass Lake',
 'The God of Small Things',
 'The Golden Compass (His Dark Materials, Book 1)',
 'The Great Gatsby',
 'The Green Mile',
 'The Grilling Season',
 'The Guardian',
 'The Gunslinger (The Dark Tower, Book 1)',
 "The Handmaid's Tale",
 "The Hitchhiker's Guide to the Galaxy",
 'The Hobbit : The Enchanting Prelude to The Lord of the Rings',
 'The Honk and Holler Opening Soon',
 'The Horse Whisperer',
 'The Hot Zone',
 'The Hours : A Novel',
 'The Hours: A Novel',
 'The House of the Spirits',
 'The Hundred Secret Senses',
 'The Hunt for Red October',
 "The Idiot Girls' Action Adventure Club",
 'The Jester',
 'The Joy Luck Club',
 'The Killing Game: Only One Can Win...and the Loser Dies',
 'The King of Torts',
 'The Kiss',
 "The Kitchen God's Wife",
 'The Last Precinct',
 'The Last Time They Met : A Novel',
 'The Little Friend',
 'The Little Prince',
 'The Long Road Home',
 'The Loop',
 "The Lost Boy: A Foster Child's Search for the Love of a Family",
 'The Lost World',
 'The Lottery Winner : Alvirah And Willy Stories',
 'The Lovely Bones: A Novel',
 'The Mists of Avalon',
 'The Most Wanted',
 'The Mulberry Tree',
 'The Mummy or Ramses the Damned',
 'The Murder Book',
 'The Nanny Diaries: A Novel',
 'The Next Accident',
 "The No. 1 Ladies' Detective Agency (Today Show Book Club #8)",
 'The Notebook',
 'The Other Boleyn Girl',
 'The Partner',
 'The Pelican Brief',
 'The Perfect Storm : A True Story of Men Against the Sea',
 'The Phantom Tollbooth',
 'The Pillars of the Earth',
 "The Pilot's Wife : A Novel",
 "The Plains of Passage (Earth's Children (Paperback))",
 'The Poisonwood Bible',
 'The Poisonwood Bible: A Novel',
 'The Prince of Tides',
 "The Princess Bride: S Morgenstern's Classic Tale of True Love and High Adventure",
 'The Promise',
 'The Pull of the Moon',
 'The Queen of the Damned (Vampire Chronicles (Paperback))',
 'The Rainmaker',
 'The Rapture of Canaan',
 'The Reader',
 'The Red Tent (Bestselling Backlist)',
 'The Reef',
 'The Regulators',
 'The Reptile Room (A Series of Unfortunate Events, Book 2)',
 'The Rescue',
 'The Return Journey',
 'The Return of the King (The Lord of the Rings, Part 3)',
 'The Robber Bride',
 'The Runaway Jury',
 'The Sands of Time',
 'The Saving Graces: A Novel',
 'The Search',
 'The Secret Garden',
 'The Secret Life of Bees',
 'The Shining',
 'The Shipping News : A Novel',
 'The Simple Truth',
 'The Smoke Jumper',
 'The Stone Diaries',
 'The Street Lawyer',
 'The Subtle Knife (His Dark Materials, Book 2)',
 'The Sum of All Fears (Jack Ryan Novels)',
 'The Summerhouse',
 'The Summons',
 'The Surgeon',
 "The Sweet Potato Queens' Book of Love",
 'The Switch',
 'The Tale of the Body Thief (Vampire Chronicles (Paperback))',
 'The Talisman',
 'The Tao of Pooh',
 'The Temple of My Familiar',
 'The Terminal Man',
 'The Testament',
 'The Thorn Birds',
 'The Tommyknockers',
 'The Two Towers (The Lord of the Rings, Part 2)',
 'The Ugly Duckling',
 'The Valley of Horses',
 'The Vampire Lestat (Vampire Chronicles, Book II)',
 'The Villa',
 'The Virgin Suicides',
 'The Wedding',
 'The Weight of Water : A Novel Tag: Author of Resistance and Strange Fits of Passion',
 'The Winner',
 'The Witching Hour (Lives of the Mayfair Witches)',
 'The Witness',
 'The Woman Next Door',
 'Thinner',
 'Three Fates',
 'Three Junes',
 'Three To Get Deadly : A Stephanie Plum Novel (A Stephanie Plum Novel)',
 'Timeline',
 'Tis : A Memoir',
 'Tis: A Memoir',
 'To Kill a Mockingbird',
 'To the Nines: A Stephanie Plum Novel',
 "Tom Clancy's Op-Center (Tom Clancy's Op Center (Paperback))",
 'Touching Evil',
 'Tough Cookie',
 'Toxin',
 'Tribulation Force: The Continuing Drama of Those Left Behind (Left Behind No. 2)',

In [514]:
image['ISBN'][image['Book-Title'] == 'Body of Lies'][0:1].values[0]

'0553582143'

In [543]:
def get_ISBN(book_name):
    ISBN=[]
    for i in book_name:
        ISBN.append(image['ISBN'][image['Book-Title'] == i][0:1].values[0])
    return ISBN

In [557]:
get_ISBN(['Bastard Out of Carolina','Deck the Halls (Holiday Classics)',
 'Degree of Guilt',
 'Deja Dead',
 'Desperation',
 'Devices and Desires',
 'Different Seasons',
 'Digital Fortress : A Thriller',
 'Disclosure'])

['0452269571',
 '0743418131',
 '034538184X',
 '0671011367',
 '0451188462',
 '0446359750',
 '0451124340',
 '0312995423',
 '0345391055']

In [517]:
get_ISBN('Bag of Bones')

'067102423X'

In [520]:
get_ISBN("Don't Sweat the Small Stuff and It's All Small Stuff : Simple Ways to Keep the Little Things from Taking Over Your Life (Don't Sweat the Small Stuff Series)")

'0786881852'

In [570]:
def get_ISBN(book_name):
    ISBN=[]
    for i in book_name:
        ISBN.append(image['ISBN'][image['Book-Title'] == i][0:1].values[0])
    return ISBN

def fetch_image(book_name):
    ISBN=[]
    for i in get_ISBN(book_name):
        ISBN.append(i)
        print("view-source:https://www.googleapis.com/books/v1/volumes?q=isbn:".format(ISBN))

In [571]:
fetch_image('Disclosure')

IndexError: index 0 is out of bounds for axis 0 with size 0

In [567]:
get_ISBN(['Bastard Out of Carolina','Deck the Halls (Holiday Classics)',
 'Degree of Guilt',
 'Deja Dead',
 'Desperation',
 'Devices and Desires',
 'Different Seasons',
 'Digital Fortress : A Thriller',
 'Disclosure'])

['0452269571',
 '0743418131',
 '034538184X',
 '0671011367',
 '0451188462',
 '0446359750',
 '0451124340',
 '0312995423',
 '0345391055']

In [ ]:
def get_ISBN(book_name):
    ISBN=[]
    for i in book_name:
        ISBN.append(image['ISBN'][image['Book-Title'] == i][0:1].values[0])
    return ISBN

In [656]:
image

,ISBN,Book-Title,Image-URL-M
0,0195153448,Classical Mythology,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,http://images.amazon.com/images/P/0393045218.0...
...,...,...,...
271355,0440400988,There's a Bat in Bunk Five,http://images.amazon.com/images/P/0440400988.0...
271356,0525447644,From One to One Hundred,http://images.amazon.com/images/P/0525447644.0...
271357,006008667X,Lily Dale : The True Story of the Town that Ta...,http://images.amazon.com/images/P/006008667X.0...
271358,0192126040,Republic (World's Classics),http://images.amazon.com/images/P/0192126040.0...
271359,0767409752,A Guided Tour of Rene Descartes' Meditations o...,http://images.amazon.com/images/P/0767409752.0...

In [663]:
ii=image.copy()

In [683]:
book_names_list=book_list['title'].values
book_names_list=list(book_names_list)
book_names_list

['1984',
 '1st to Die: A Novel',
 '2nd Chance',
 '4 Blondes',
 '84 Charing Cross Road',
 'A Bend in the Road',
 'A Case of Need',
 'A Child Called \\It\\": One Child\'s Courage to Survive"',
 'A Civil Action',
 'A Cry In The Night',
 'A Darkness More Than Night',
 'A Day Late and a Dollar Short',
 'A Fine Balance',
 'A Great Deliverance',
 'A Heartbreaking Work of Staggering Genius',
 'A Is for Alibi (Kinsey Millhone Mysteries (Paperback))',
 'A Lesson Before Dying (Vintage Contemporaries (Paperback))',
 'A Man Named Dave: A Story of Triumph and Forgiveness',
 'A Man in Full',
 'A Map of the World',
 'A Painted House',
 'A Patchwork Planet',
 'A Prayer for Owen Meany',
 'A Thin Dark Line (Mysteries &amp; Horror)',
 "A Thousand Acres (Ballantine Reader's Circle)",
 'A Time to Kill',
 "A Virtuous Woman (Oprah's Book Club (Paperback))",
 'A Walk to Remember',
 'A Widow for One Year',
 'A Wrinkle In Time',
 'A Wrinkle in Time',
 'A Year in Provence',
 "ANGELA'S ASHES",
 'Abduction',
 'About a Boy',
 'Absolute Power',
 'Acceptable Risk',
 'Accident',
 'Airframe',
 'Alaska',
 'All Around the Town',
 'All Creatures Great and Small',
 'All I Really Need to Know',
 'All That Remains (Kay Scarpetta Mysteries (Paperback))',
 'All the Pretty Horses (The Border Trilogy, Vol 1)',
 'Along Came a Spider (Alex Cross Novels)',
 'American Gods',
 'And Then You Die',
 "Angela's Ashes (MMP) : A Memoir",
 "Angela's Ashes: A Memoir",
 'Angels',
 'Angels &amp; Demons',
 'Angus, Thongs and Full-Frontal Snogging: Confessions of Georgia Nicolson',
 'Animal Dreams',
 'Animal Farm',
 'Anne Frank: The Diary of a Young Girl',
 'Anne of Avonlea (Anne of Green Gables Novels (Paperback))',
 'Anne of Green Gables (Anne of Green Gables Novels (Paperback))',
 'Anne of the Island',
 'Artemis Fowl (Artemis Fowl, Book 1)',
 'Ashes to Ashes',
 'At Home in Mitford (The Mitford Years)',
 'Atonement : A Novel',
 'B Is for Burglar (Kinsey Millhone Mysteries (Paperback))',
 'Back Roads',
 'Bag of Bones',
 'Balzac and the Little Chinese Seamstress : A Novel',
 'Bastard Out of Carolina',
 'Beach House',
 'Beach Music',
 'Before I Say Good-Bye',
 'Bel Canto: A Novel',
 'Beloved',
 'Beloved (Plume Contemporary Fiction)',
 'Betrayal in Death',
 "Big Cherry Holler: A Big Stone Gap Novel (Ballantine Reader's Circle)",
 "Big Stone Gap: A Novel (Ballantine Reader's Circle)",
 'Big Trouble',
 'Billy Straight : A Novel',
 'Birthright',
 'Bittersweet',
 'Black House',
 'Black Notice',
 'Black and Blue',
 'Bleachers',
 'Blessings',
 'Blood Work',
 'Blue Diary',
 'Body of Evidence (Kay Scarpetta Mysteries (Paperback))',
 'Body of Lies',
 'Brave New World',
 'Breath, Eyes, Memory',
 'Breathing Lessons',
 'Bridge to Terabithia',
 'Bridget Jones : The Edge of Reason',
 "Bridget Jones's Diary",
 'Bridget Jones: The Edge of Reason',
 'By the Light of the Moon',
 'C Is for Corpse (Kinsey Millhone Mysteries (Paperback))',
 "CAT'S EYE",
 'Call of the Wild',
 'Carnal Innocence',
 'Carolina Moon',
 'Carrie',
 'Cat &amp; Mouse (Alex Cross Novels)',
 'Catering to Nobody',
 'Cause of Death',
 'Certain Prey',
 "Charlotte's Web (Trophy Newbery)",
 'Charming Billy',
 'Chicken Soup for the Soul (Chicken Soup for the Soul)',
 "Chicken Soup for the Woman's Soul (Chicken Soup for the Soul Series (Paper))",
 'Chocolat',
 'Choke',
 'Chosen Prey',
 'Christine',
 'Chromosome 6',
 'Circle of Friends',
 'Clear and Present Danger (Jack Ryan Novels)',
 'Cold Mountain',
 'Cold Mountain : A Novel',
 'Cold Sassy Tree',
 'Colony',
 'Coming Home',
 'Confessions of a Shopaholic (Summer Display Opportunity)',
 'Confessions of an Ugly Stepsister : A Novel',
 'Congo',
 'Contact',
 'Contagion',
 'Coraline',
 'Couplehood',
 'Cradle and All',
 'Crazy for You',
 'Cruel &amp; Unusual (Kay Scarpetta Mysteries (Paperback))',
 'Cry Wolf',
 'Cujo',
 'D Is for Deadbeat (Kinsey Millhone Mysteries (Paperback))',
 'Daddy',
 "Daddy's Little Girl",
 'Daisy Fay and the Miracle Man',
 'Dance upon the Air (Three Sisters Island Trilogy)',
 'Dances With Wolves',
 'Dangerous',
 'Dark Angel',
 'Dark Paradise',
 'Dark Rivers of the Heart',
 'Dawn (Cutler)',
 'Dead Run',
 'Death du Jour',
 'Debt of Honor (Jack Ryan Novels)',
 'Deception Point',
 'Deck the Halls (Holiday Classics)',
 'Degree of Guilt',
 'Deja Dead',
 'Desperation',
 'Devices and Desires',
 'Different Seasons',
 'Digital Fortress : A Thriller',
 'Disclosure',
 'Divine Secrets of the Ya-Ya Sisterhood: A Novel',
 'Dolores Claiborne',
 "Don't Stand Too Close to a Naked Man",
 "Don't Sweat the Small Stuff and It's All Small Stuff : Simple Ways to Keep the Little Things from Taking Over Your Life (Don't Sweat the Small Stuff Series)",
 "Dr. Atkins' New Diet Revolution",
 'Dragon Tears',
 'Dragonfly in Amber',
 'Dream Country',
 'Dreamcatcher',
 'Drowning Ruth',
 "Drowning Ruth (Oprah's Book Club)",
 'Drums of Autumn',
 "Dude, Where's My Country?",
 'Dust to Dust',
 'Dying for Chocolate (Culinary Mysteries (Paperback))',
 'E Is for Evidence: A Kinsey Millhone Mystery (Kinsey Millhone Mysteries (Paperback))',
 'Easy Prey',
 'Echoes',
 'Ellen Foster',
 'Empire Falls',
 "Ender's Game (Ender Wiggins Saga (Paperback))",
 'Engaging The Enemy',
 'Envy',
 'Evening Class',
 "Everything's Eventual : 14 Dark Tales",
 'Exclusive',
 'Executive Orders (Jack Ryan Novels)',
 'Eyes of Prey',
 'Eyes of a Child',
 'F Is for Fugitive (Kinsey Millhone Mysteries (Paperback))',
 'FORREST GUMP (Movie Tie in)',
 'Face the Fire (Three Sisters Island Trilogy)',
 'Fahrenheit 451',
 'Faking It',
 'Fall On Your Knees (Oprah #45)',
 'Falling Angels',
 'False Memory',
 'Family Album',
 'Fast Food Nation: The Dark Side of the All-American Meal',
 'Fast Women',
 'Fat Tuesday',
 'Fatal Cure',
 'Fatherhood',
 'Fear Nothing',
 'Final Target',
 'Fine Things',
 'Fingersmith',
 'Five Days in Paris',
 'Five Quarters of the Orange',
 'Flesh and Blood',
 'Forever... : A Novel of Good and Evil, Love and Hope',
 "Fortune's Rocks : A Novel",
 "Fortune's Rocks: A Novel",
 "Foucault's Pendulum",
 'Four Blind Mice',
 'Four Past Midnight',
 'Four To Score (A Stephanie Plum Novel)',
 'Fried Green Tomatoes at the Whistle Stop Cafe',
 "From Potter's Field",
 'From the Corner of His Eye',
 "Full House (Janet Evanovich's Full Series)",
 "Full Tilt (Janet Evanovich's Full Series)",
 'G Is for Gumshoe (Kinsey Millhone Mysteries (Paperback))',
 'GARDEN OF SHADOWS (Dollanger Saga (Paperback))',
 "Gerald's Game",
 'Girl in Hyacinth Blue',
 'Girl with a Pearl Earring',
 'Girl, Interrupted',
 'Good Omens',
 'Good in Bed',
 'Gorky Park',
 'Granny Dan',
 'Guardian Angel',
 'Guilty Pleasures (Anita Blake Vampire Hunter (Paperback))',
 'Guilty as Sin',
 'H Is for Homicide (Kinsey Millhone Mysteries (Paperback))',
 'Hannibal',
 'Hard Eight : A Stephanie Plum Novel (A Stephanie Plum Novel)',
 'Harry Potter and the Chamber of Secrets (Book 2)',
 'Harry Potter and the Goblet of Fire (Book 4)',
 'Harry Potter and the Order of the Phoenix (Book 5)',
 'Harry Potter and the Prisoner of Azkaban (Book 3)',
 "Harry Potter and the Sorcerer's Stone (Book 1)",
 "Harry Potter and the Sorcerer's Stone (Harry Potter (Paperback))",
 'Harvest',
 'Heart of the Sea (Irish Trilogy)',
 'Heartbeat',
 'Heartbreaker',
 'Hearts In Atlantis',
 'Hearts in Atlantis',
 'Heaven and Earth (Three Sisters Island Trilogy)',
 'Hemlock Bay',
 'Here on Earth',
 'Hide &amp; Seek',
 'Hideaway',
 'High Fidelity',
 'High Five (A Stephanie Plum Novel)',
 'Holes (Yearling Newbery)',
 'Homecoming',
 'Homeport',
 "Hornet's Nest",
 'Hot Six : A Stephanie Plum Novel (A Stephanie Plum Novel)',
 'House of Sand and Fog',
 'How Stella Got Her Groove Back',
 'How to Be Good',
 'How to Make an American Quilt',
 'I Capture the Castle',
 'I Is for Innocent',
 'I Know This Much Is True',
 "I Know This Much Is True (Oprah's Book Club)",
 'I Know Why the Caged Bird Sings',
 "I'll Be Seeing You",
 'Icebound',
 'Icy Sparks',
 'If Only It Were True',
 'If Tomorrow Comes',
 'Impulse',
 'In Her Shoes : A Novel',
 'Inner Harbor (Quinn Brothers (Paperback))',
 'Insomnia',
 'Intensity',
 'Interview with the Vampire',
 'Into Thin Air : A Personal Account of the Mt. Everest Disaster',
 'Into the Wild',
 'Invasion',
 'Irish Hearts',
 'Isle of Dogs',
 'It',
 'It Was on Fire When I Lay Down on It',
 "It's Always Something",
 'J Is for Judgment',
 'Jack &amp; Jill (Alex Cross Novels)',
 'Jacob Have I Loved',
 'Jemima J: A Novel About Ugly Ducklings and Swans',
 'Jewel',
 "Jewel (Oprah's Book Club)",
 'Jewels of the Sun (Irish Trilogy)',
 'Journey',
 'Jurassic Park',
 'K Is for Killer (Kinsey Millhone Mysteries (Paperback))',
 'Kaleidoscope',
 'Key of Knowledge (Key Trilogy (Paperback))',
 'Key of Light (Key Trilogy (Paperback))',
 'Key of Valor (Roberts, Nora. Key Trilogy, 3.)',
 'Killjoy',
 'Kiss the Girls',
 'L Is for Lawless',
 'Ladder of Years',
 'Lake Wobegon Days',
 'Lake Wobegon days',
 "Lamb : The Gospel According to Biff, Christ's Childhood Pal",
 'Last Chance Saloon',
 'Last Man Standing',
 "Left Behind: A Novel of the Earth's Last Days (Left Behind No. 1)",
 'Let Me Call You Sweetheart',
 'Life of Pi',
 'Lightning',
 'Like Water for Chocolate : A Novel in Monthly Installments with Recipes, Romances, and Home Remedies',
 'Like Water for Chocolate: A Novel in Monthly Installments With Recipes, Romances and Home Remedies',
 'Like Water for Chocolate: A Novel in Monthly Installments, With Recipes, Romances, and Home Remedies',
 'Little Altars Everywhere: A Novel',
 'Long After Midnight',
 'Lord of the Flies',
 'Love in the Time of Cholera (Penguin Great Books of the 20th Century)',
 'Loves Music, Loves to Dance',
 'Lucky : A Memoir',
 'Lucky Man: A Memoir',
 'M Is for Malice',
 'Macgregor Brides (Macgregors)',
 'Macgregor Grooms (Macgregors)',
 'Master of the Game',
 'Matilda',
 'Me Talk Pretty One Day',
 'Men Are from Mars, Women Are from Venus: A Practical Guide for Improving Communication and Getting What You Want in Your Relationships',
 'Mercy',
 'Message from Nam',
 'Message in a Bottle',
 'Middlesex: A Novel',
 'Midnight',
 'Midnight Bayou',
 'Midnight in the Garden of Good and Evil',
 'Midnight in the Garden of Good and Evil: A Savannah Story',
 'Midwives: A Novel',
 'Mind Prey',
 'Mirror Image',
 'Misery',
 'Miss Julia Speaks Her Mind : A Novel',
 'Monster : A Novel (Alex Delaware Novels (Paperback))',
 'Montana Sky',
 'Moo',
 'Moonlight Becomes You',
 'Morality for Beautiful Girls (No.1 Ladies Detective Agency)',
 'Mortal Fear',
 'Mortal Prey',
 'Mother of Pearl',
 'Mr. Murder',
 'My Gal Sunday',
 'Mystic River',
 'N Is for Noose',
 'Naked',
 'Needful Things',
 'Nerd in Shining Armor',
 'Neuromancer (Remembering Tomorrow)',
 'Neverwhere',
 'Nickel and Dimed: On (Not) Getting By in America',
 'Nicolae: The Rise of Antichrist (Left Behind No. 3)',
 'Night',
 'Night Prey',
 'Night Sins',
 'Night Whispers',
 'Nightmares &amp; Dreamscapes',
 'Nights in Rodanthe',
 'No Greater Love',
 'No Safe Place',
 'Notes from a Small Island',
 'Nothing Lasts Forever',
 'Now You See Her',
 'On the Street Where You Live',
 'One Door Away from Heaven',
 'One True Thing',
 'One for the Money (A Stephanie Plum Novel)',
 'One for the Money (Stephanie Plum Novels (Paperback))',
 'Oryx and Crake',
 'Outlander',
 'Over the Edge',
 'P Is for Peril',
 'Paradise',
 'Patriot Games (Jack Ryan Novels)',
 'Pay It Forward',
 'Peace Like a River',
 'Pet Sematary',
 'Phantoms',
 'Pigs in Heaven',
 'Plainsong (Vintage Contemporaries)',
 'Pleading Guilty',
 'Plum Island',
 'Point of Origin',
 'Politically Correct Bedtime Stories: Modern Tales for Our Life and Times',
 'Pop Goes the Weasel',
 'Portrait in Death',
 'Possession : A Romance',
 'Postmortem',
 'Practical Magic',
 'Presumed Innocent',
 "Pretend You Don't See Her",
 'Pride and Prejudice',
 'Primary Colors: A Novel of Politics',
 'Prime Cut',
 'Prodigal Summer',
 'Prodigal Summer: A Novel',
 'Purity in Death',
 'Q Is for Quarry',
 'Quentins',
 'Rainbow Six',
 'Range of Motion',
 'Reap the Wind',
 'Rebecca',
 'Red Dragon',
 'Red Storm Rising',
 'Remember Me',
 'Riptide',
 'Rising Sun',
 'Rising Tides',
 "River's End",
 'River, Cross My Heart',
 'Rose Madder',
 'Roses Are Red (Alex Cross Novels)',
 'Rules of Prey',
 'SHIPPING NEWS',
 'STONES FROM THE RIVER',
 'Sacred Sins',
 'Saint Maybe',
 'Sanctuary',
 'Saving Faith',
 'Scarlet Feather',
 'Scarlett : The Sequel to Margaret Mitchell\'s \\Gone With the Wind\\""',
 "Schindler's List",
 'Sea Glass: A Novel',
 'Sea Swept (Quinn Brothers (Paperback))',
 'Seabiscuit',
 'Seabiscuit: An American Legend',
 'Second Nature',
 'Secret History',
 'Secrets',
 'Seize the Night',
 'September',
 'Seven Habits Of Highly Effective People',
 'Seven Up (A Stephanie Plum Novel)',
 'Shadow Prey',
 'Shadowfires',
 'Shattered',
 "She's Come Undone (Oprah's Book Club (Paperback))",
 "She's Come Undone (Oprah's Book Club)",
 'Shell Seekers',
 'Shopaholic Takes Manhattan (Summer Display Opportunity)',
 'Shopaholic Ties the Knot',
 'Sick Puppy',
 'Silence of the Lambs',
 'Silent Witness',
 'Sisterhood of the Traveling Pants',
 'Skeleton Crew',
 'Skipping Christmas',
 'Slammerkin',
 "Slaughterhouse Five or the Children's Crusade: A Duty Dance With Death",
 'Sleepers',
 'Slow Waltz in Cedar Bend',
 'Small Town Girl',
 'Smart Women',
 "Smilla's Sense of Snow",
 'Snow Falling on Cedars',
 'Sole Survivor',
 "Song of Solomon (Oprah's Book Club (Paperback))",
 "Songs in Ordinary Time (Oprah's Book Club (Paperback))",
 "Sophie's World: A Novel About the History of Philosophy",
 'Southern Cross',
 'Sphere',
 'Standoff',
 'Stanislaski Brothers (Silhouette Promo)',
 'Still Waters',
 'Stillwatch',
 'Strangers',
 'Stupid White Men ...and Other Sorry Excuses for the State of the Nation!',
 'Sudden Prey',
 'Summer Pleasures',
 'Summer Sisters',
 "Suzanne's Diary for Nicholas",
 'Table For Two',
 'Tales of a Fourth Grade Nothing',
 'Taltos: Lives of the Mayfair Witches',
 'Tara Road',
 'Tears of the Giraffe (No.1 Ladies Detective Agency)',
 'Tears of the Moon (Irish Trilogy)',
 'Tell Me Lies (Tell Me Lies)',
 'Tell Me Your Dreams',
 'Tell No One',
 'Temptation',
 'That Camden Summer',
 'The Accidental Tourist',
 'The Alchemist: A Fable About Following Your Dream',
 'The Alibi',
 'The Alienist',
 'The Amazing Adventures of Kavalier &amp; Clay',
 'The Amber Spyglass (His Dark Materials, Book 3)',
 'The Andromeda Strain',
 'The Angel of Darkness',
 'The Apprentice',
 'The Bachelor (Warner Books Contemporary Romance)',
 'The Bad Beginning (A Series of Unfortunate Events, Book 1)',
 'The Bad Place',
 'The Beach House',
 'The Bean Trees',
 'The Blind Assassin',
 'The Blue Nowhere : A Novel',
 'The Bluest Eye',
 'The Body Farm',
 "The Bonesetter's Daughter",
 'The Bonfire of the Vanities',
 "The Book of Ruth (Oprah's Book Club (Paperback))",
 'The Bourne Identity',
 'The Bourne Supremacy',
 'The Bourne Ultimatum',
 'The Boy Next Door',
 'The Brethren',
 'The Bridges of Madison County',
 'The Burden of Proof',
 'The Cardinal of the Kremlin (Jack Ryan Novels)',
 'The Carousel',
 'The Catcher in the Rye',
 'The Celestine Prophecy (Celestine Prophecy)',
 'The Chamber',
 'The Cider House Rules',
 "The Clan of the Cave Bear (Earth's Children (Paperback))",
 'The Client',
 'The Clinic (Alex Delaware Novels (Paperback))',
 'The Color Purple',
 "The Color of Water: A Black Man's Tribute to His White Mother",
 'The Copper Beech',
 'The Cradle Will Fall',
 'The Crimson Petal and the White',
 'The Da Vinci Code',
 'The Dark Half',
 'The Dead Zone',
 'The Deep End of the Ocean',
 'The Devil Wears Prada : A Novel',
 'The Diary of Ellen Rimbauer: My Life at Rose Red',
 'The Divine Secrets of the Ya-Ya Sisterhood: A Novel',
 'The Dogs of Babel (Today Show Book Club #12)',
 'The Door to December',
 'The Drawing of the Three (The Dark Tower, Book 2)',
 'The Edge',
 'The Eight',
 'The Empty Chair',
 'The English Patient',
 'The Eyre Affair: A Novel',
 'The Face of Deception',
 'The Fellowship of the Ring (The Lord of the Rings, Part 1)',
 'The Firm',
 'The First Counsel',
 'The First Wives Club Movie Tie In',
 'The Five People You Meet in Heaven',
 'The Fourth Hand',
 "The General's Daughter",
 'The Genesis Code',
 'The Ghost',
 'The Gift',
 'The Girl Who Loved Tom Gordon',
 "The Girls' Guide to Hunting and Fishing",
 'The Giver (21st Century Reference)',
 'The Glass Lake',
 'The God of Small Things',
 'The Golden Compass (His Dark Materials, Book 1)',
 'The Great Gatsby',
 'The Green Mile',
 'The Grilling Season',
 'The Guardian',
 'The Gunslinger (The Dark Tower, Book 1)',
 "The Handmaid's Tale",
 "The Hitchhiker's Guide to the Galaxy",
 'The Hobbit : The Enchanting Prelude to The Lord of the Rings',
 'The Honk and Holler Opening Soon',
 'The Horse Whisperer',
 'The Hot Zone',
 'The Hours : A Novel',
 'The Hours: A Novel',
 'The House of the Spirits',
 'The Hundred Secret Senses',
 'The Hunt for Red October',
 "The Idiot Girls' Action Adventure Club",
 'The Jester',
 'The Joy Luck Club',
 'The Killing Game: Only One Can Win...and the Loser Dies',
 'The King of Torts',
 'The Kiss',
 "The Kitchen God's Wife",
 'The Last Precinct',
 'The Last Time They Met : A Novel',
 'The Little Friend',
 'The Little Prince',
 'The Long Road Home',
 'The Loop',
 "The Lost Boy: A Foster Child's Search for the Love of a Family",
 'The Lost World',
 'The Lottery Winner : Alvirah And Willy Stories',
 'The Lovely Bones: A Novel',
 'The Mists of Avalon',
 'The Most Wanted',
 'The Mulberry Tree',
 'The Mummy or Ramses the Damned',
 'The Murder Book',
 'The Nanny Diaries: A Novel',
 'The Next Accident',
 "The No. 1 Ladies' Detective Agency (Today Show Book Club #8)",
 'The Notebook',
 'The Other Boleyn Girl',
 'The Partner',
 'The Pelican Brief',
 'The Perfect Storm : A True Story of Men Against the Sea',
 'The Phantom Tollbooth',
 'The Pillars of the Earth',
 "The Pilot's Wife : A Novel",
 "The Plains of Passage (Earth's Children (Paperback))",
 'The Poisonwood Bible',
 'The Poisonwood Bible: A Novel',
 'The Prince of Tides',
 "The Princess Bride: S Morgenstern's Classic Tale of True Love and High Adventure",
 'The Promise',
 'The Pull of the Moon',
 'The Queen of the Damned (Vampire Chronicles (Paperback))',
 'The Rainmaker',
 'The Rapture of Canaan',
 'The Reader',
 'The Red Tent (Bestselling Backlist)',
 'The Reef',
 'The Regulators',
 'The Reptile Room (A Series of Unfortunate Events, Book 2)',
 'The Rescue',
 'The Return Journey',
 'The Return of the King (The Lord of the Rings, Part 3)',
 'The Robber Bride',
 'The Runaway Jury',
 'The Sands of Time',
 'The Saving Graces: A Novel',
 'The Search',
 'The Secret Garden',
 'The Secret Life of Bees',
 'The Shining',
 'The Shipping News : A Novel',
 'The Simple Truth',
 'The Smoke Jumper',
 'The Stone Diaries',
 'The Street Lawyer',
 'The Subtle Knife (His Dark Materials, Book 2)',
 'The Sum of All Fears (Jack Ryan Novels)',
 'The Summerhouse',
 'The Summons',
 'The Surgeon',
 "The Sweet Potato Queens' Book of Love",
 'The Switch',
 'The Tale of the Body Thief (Vampire Chronicles (Paperback))',
 'The Talisman',
 'The Tao of Pooh',
 'The Temple of My Familiar',
 'The Terminal Man',
 'The Testament',
 'The Thorn Birds',
 'The Tommyknockers',
 'The Two Towers (The Lord of the Rings, Part 2)',
 'The Ugly Duckling',
 'The Valley of Horses',
 'The Vampire Lestat (Vampire Chronicles, Book II)',
 'The Villa',
 'The Virgin Suicides',
 'The Wedding',
 'The Weight of Water : A Novel Tag: Author of Resistance and Strange Fits of Passion',
 'The Winner',
 'The Witching Hour (Lives of the Mayfair Witches)',
 'The Witness',
 'The Woman Next Door',
 'Thinner',
 'Three Fates',
 'Three Junes',
 'Three To Get Deadly : A Stephanie Plum Novel (A Stephanie Plum Novel)',
 'Timeline',
 'Tis : A Memoir',
 'Tis: A Memoir',
 'To Kill a Mockingbird',
 'To the Nines: A Stephanie Plum Novel',
 "Tom Clancy's Op-Center (Tom Clancy's Op Center (Paperback))",
 'Touching Evil',
 'Tough Cookie',
 'Toxin',
 'Tribulation Force: The Continuing Drama of Those Left Behind (Left Behind No. 2)',

In [685]:
ii=image[image['Book-Title'].isin(book_names_list)]
ii

,ISBN,Book-Title,Image-URL-M
5,0399135782,The Kitchen God's Wife,http://images.amazon.com/images/P/0399135782.0...
18,0440234743,The Testament,http://images.amazon.com/images/P/0440234743.0...
19,0452264464,Beloved (Plume Contemporary Fiction),http://images.amazon.com/images/P/0452264464.0...
26,0971880107,Wild Animus,http://images.amazon.com/images/P/0971880107.0...
27,0345402871,Airframe,http://images.amazon.com/images/P/0345402871.0...
...,...,...,...
268974,0745168086,The Handmaid's Tale,http://images.amazon.com/images/P/0745168086.0...
269379,0582060184,1984,http://images.amazon.com/images/P/0582060184.0...
269944,0805041494,Still Waters,http://images.amazon.com/images/P/0805041494.0...
270659,0553290703,Lightning,http://images.amazon.com/images/P/0553290703.0...
271169,0395647398,"The Two Towers (The Lord of the Rings, Part 2)",http://images.amazon.com/images/P/0395647398.0...

In [686]:
ii.nunique()

ISBN           2597
Book-Title      742
Image-URL-M    2555
dtype: int64

In [695]:
ii.reset_index(inplace=True)

In [696]:
ii

,index,ISBN,Book-Title,Image-URL-M
0,5,0399135782,The Kitchen God's Wife,http://images.amazon.com/images/P/0399135782.0...
1,18,0440234743,The Testament,http://images.amazon.com/images/P/0440234743.0...
2,19,0452264464,Beloved (Plume Contemporary Fiction),http://images.amazon.com/images/P/0452264464.0...
3,26,0971880107,Wild Animus,http://images.amazon.com/images/P/0971880107.0...
4,27,0345402871,Airframe,http://images.amazon.com/images/P/0345402871.0...
...,...,...,...,...
2592,268974,0745168086,The Handmaid's Tale,http://images.amazon.com/images/P/0745168086.0...
2593,269379,0582060184,1984,http://images.amazon.com/images/P/0582060184.0...
2594,269944,0805041494,Still Waters,http://images.amazon.com/images/P/0805041494.0...
2595,270659,0553290703,Lightning,http://images.amazon.com/images/P/0553290703.0...
2596,271169,0395647398,"The Two Towers (The Lord of the Rings, Part 2)",http://images.amazon.com/images/P/0395647398.0...

In [687]:
def get_link_shorten(links):
    for i in range(len(links)):
        links[i]=links[i][0:-16]
    return links

In [688]:
link=ii['Image-URL-M']

In [698]:
get_link_shorten(ii['Image-URL-M'])

C:\Users\adila\AppData\Local\Temp/ipykernel_19632/4199766331.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  links[i]=links[i][0:-16]

0       http://images.amazon.com/images/P/0399135782
1       http://images.amazon.com/images/P/0440234743
2       http://images.amazon.com/images/P/0452264464
3       http://images.amazon.com/images/P/0971880107
4       http://images.amazon.com/images/P/0345402871
                            ...
2592    http://images.amazon.com/images/P/0745168086
2593    http://images.amazon.com/images/P/0582060184
2594    http://images.amazon.com/images/P/0805041494
2595    http://images.amazon.com/images/P/0553290703
2596    http://images.amazon.com/images/P/0395647398
Name: Image-URL-M, Length: 2597, dtype: object

In [699]:
ii

,index,ISBN,Book-Title,Image-URL-M
0,5,0399135782,The Kitchen God's Wife,http://images.amazon.com/images/P/0399135782
1,18,0440234743,The Testament,http://images.amazon.com/images/P/0440234743
2,19,0452264464,Beloved (Plume Contemporary Fiction),http://images.amazon.com/images/P/0452264464
3,26,0971880107,Wild Animus,http://images.amazon.com/images/P/0971880107
4,27,0345402871,Airframe,http://images.amazon.com/images/P/0345402871
...,...,...,...,...
2592,268974,0745168086,The Handmaid's Tale,http://images.amazon.com/images/P/0745168086
2593,269379,0582060184,1984,http://images.amazon.com/images/P/0582060184
2594,269944,0805041494,Still Waters,http://images.amazon.com/images/P/0805041494
2595,270659,0553290703,Lightning,http://images.amazon.com/images/P/0553290703
2596,271169,0395647398,"The Two Towers (The Lord of the Rings, Part 2)",http://images.amazon.com/images/P/0395647398

In [757]:
def get_ISBN(book_name):
    ISBN=[]
    for i in book_name:
        ISBN.append(ii['ISBN'][ii['Book-Title'] == i][0:1].values[0])
    return ISBN

def get_link(book_name):
    link=[]
    for i in get_ISBN(book_name):
        link.append(ii['Image-URL-M'][ii['ISBN'] == i][0:1].values[0])
    return link

In [758]:
ii['Image-URL-M'][ii['Book-Title'] == '2nd Chance'][0:1]

147    http://images.amazon.com/images/P/0316693200
Name: Image-URL-M, dtype: object

In [759]:
get_link(['1984',
 '1st to Die: A Novel',
 '2nd Chance'])

['http://images.amazon.com/images/P/0451524934',
 'http://images.amazon.com/images/P/0446610038',
 'http://images.amazon.com/images/P/0316693200']

In [707]:
get_ISBN(['1984',
 '1st to Die: A Novel',
 '2nd Chance'])

['0451524934', '0446610038', '0316693200']

In [760]:
get_link(book_names_list)

['http://images.amazon.com/images/P/0451524934',
 'http://images.amazon.com/images/P/0446610038',
 'http://images.amazon.com/images/P/0316693200',
 'http://images.amazon.com/images/P/0451203895',
 'http://images.amazon.com/images/P/0860074382',
 'http://images.amazon.com/images/P/0446527785',
 'http://images.amazon.com/images/P/0451183665',
 'http://images.amazon.com/images/P/1558743669',
 'http://images.amazon.com/images/P/0679772677',
 'http://images.amazon.com/images/P/0671886665',
 'http://images.amazon.com/images/P/0446667900',
 'http://images.amazon.com/images/P/0451204948',
 'http://images.amazon.com/images/P/140003065X',
 'http://images.amazon.com/images/P/0553278029',
 'http://images.amazon.com/images/P/0375725784',
 'http://images.amazon.com/images/P/0553279912',
 'http://images.amazon.com/images/P/0375702709',
 'http://images.amazon.com/images/P/0525945210',
 'http://images.amazon.com/images/P/0374270325',
 'http://images.amazon.com/images/P/0385500769',
 'http://images.amazon.com/images/P/044023722X',
 'http://images.amazon.com/images/P/080411918X',
 'http://images.amazon.com/images/P/0345361792',
 'http://images.amazon.com/images/P/0553571885',
 'http://images.amazon.com/images/P/0449907481',
 'http://images.amazon.com/images/P/0440211727',
 'http://images.amazon.com/images/P/0375703063',
 'http://images.amazon.com/images/P/0446608955',
 'http://images.amazon.com/images/P/0345424719',
 'http://images.amazon.com/images/P/0440498058',
 'http://images.amazon.com/images/P/0440998050',
 'http://images.amazon.com/images/P/0679731148',
 'http://images.amazon.com/images/P/0684874350',
 'http://images.amazon.com/images/P/042517736X',
 'http://images.amazon.com/images/P/1573227331',
 'http://images.amazon.com/images/P/0446519960',
 'http://images.amazon.com/images/P/0425151867',
 'http://images.amazon.com/images/P/0385306024',
 'http://images.amazon.com/images/P/0345402871',
 'http://images.amazon.com/images/P/0671001787',
 'http://images.amazon.com/images/P/0671793489',
 'http://images.amazon.com/images/P/0553122509',
 'http://images.amazon.com/images/P/080410526X',
 'http://images.amazon.com/images/P/0380718332',
 'http://images.amazon.com/images/P/0679744398',
 'http://images.amazon.com/images/P/0446364193',
 'http://images.amazon.com/images/P/0380789035',
 'http://images.amazon.com/images/P/0553579983',
 'http://images.amazon.com/images/P/0684872153',
 'http://images.amazon.com/images/P/068484267X',
 'http://images.amazon.com/images/P/0060008024',
 'http://images.amazon.com/images/P/0671027360',
 'http://images.amazon.com/images/P/0064472272',
 'http://images.amazon.com/images/P/0060921145',
 'http://images.amazon.com/images/P/0451526341',
 'http://images.amazon.com/images/P/0553296981',
 'http://images.amazon.com/images/P/0553213148',
 'http://images.amazon.com/images/P/055321313X',
 'http://images.amazon.com/images/P/0553213172',
 'http://images.amazon.com/images/P/0786817070',
 'http://images.amazon.com/images/P/0553579606',
 'http://images.amazon.com/images/P/014025448X',
 'http://images.amazon.com/images/P/038572179X',
 'http://images.amazon.com/images/P/0553280341',
 'http://images.amazon.com/images/P/0451202341',
 'http://images.amazon.com/images/P/067102423X',
 'http://images.amazon.com/images/P/0385722206',
 'http://images.amazon.com/images/P/0452269571',
 'http://images.amazon.com/images/P/1551668998',
 'http://images.amazon.com/images/P/0385413041',
 'http://images.amazon.com/images/P/0671004573',
 'http://images.amazon.com/images/P/0060934417',
 'http://images.amazon.com/images/P/0452280621',
 'http://images.amazon.com/images/P/0452264464',
 'http://images.amazon.com/images/P/0425178579',
 'http://images.amazon.com/images/P/0345445848',
 'http://images.amazon.com/images/P/0345438329',
 'http://images.amazon.com/images/P/0425184129',
 'http://images.amazon.com/images/P/0345413865',
 'http://images.amazon.com/images/P/0515137111',
 'http://images.amazon.com/images/P/0440224845',
 'http://images.amazon.com/images/P/0375504397',
 'http://images.amazon.com/images/P/0399145087',
 'http://images.amazon.com/images/P/0440226104',
 'http://images.amazon.com/images/P/0385511612',
 'http://images.amazon.com/images/P/0375502238',
 'http://images.amazon.com/images/P/0446602620',
 'http://images.amazon.com/images/P/0425184943',
 'http://images.amazon.com/images/P/0380717018',
 'http://images.amazon.com/images/P/0553582143',
 'http://images.amazon.com/images/P/0060809833',
 'http://images.amazon.com/images/P/037570504X',
 'http://images.amazon.com/images/P/042511774X',
 'http://images.amazon.com/images/P/006073941X',
 'http://images.amazon.com/images/P/0670892963',
 'http://images.amazon.com/images/P/0330332775',
 'http://images.amazon.com/images/P/0140298479',
 'http://images.amazon.com/images/P/0553582763',
 'http://images.amazon.com/images/P/0553280368',
 'http://images.amazon.com/images/P/0553282476',
 'http://images.amazon.com/images/P/1559029838',
 'http://images.amazon.com/images/P/0553295977',
 'http://images.amazon.com/images/P/0515130389',
 'http://images.amazon.com/images/P/0451157443',
 'http://images.amazon.com/images/P/0446606189',
 'http://images.amazon.com/images/P/044922046X',
 'http://images.amazon.com/images/P/0425158616',
 'http://images.amazon.com/images/P/0425174271',
 'http://images.amazon.com/images/P/0064400557',
 'http://images.amazon.com/images/P/038533334X',
 'http://images.amazon.com/images/P/155874262X',
 'http://images.amazon.com/images/P/1558744150',
 'http://images.amazon.com/images/P/0552998486',
 'http://images.amazon.com/images/P/0385720920',
 'http://images.amazon.com/images/P/0425182878',
 'http://images.amazon.com/images/P/0451139739',
 'http://images.amazon.com/images/P/0425161242',
 'http://images.amazon.com/images/P/0440211263',
 'http://images.amazon.com/images/P/0425122123',
 'http://images.amazon.com/images/P/0871136791',
 'http://images.amazon.com/images/P/0375700757',
 'http://images.amazon.com/images/P/038531258X',
 'http://images.amazon.com/images/P/0061099708',
 'http://images.amazon.com/images/P/0312958129',
 'http://images.amazon.com/images/P/0385335482',
 'http://images.amazon.com/images/P/0060987529',
 'http://images.amazon.com/images/P/0345378490',
 'http://images.amazon.com/images/P/0505524996',
 'http://images.amazon.com/images/P/0425155943',
 'http://images.amazon.com/images/P/0380977788',
 'http://images.amazon.com/images/P/0553096834',
 'http://images.amazon.com/images/P/0316690619',
 'http://images.amazon.com/images/P/0312198493',
 'http://images.amazon.com/images/P/0380718340',
 'http://images.amazon.com/images/P/055356160X',
 'http://images.amazon.com/images/P/8878242357',
 'http://images.amazon.com/images/P/0553271636',
 'http://images.amazon.com/images/P/0440207622',
 'http://images.amazon.com/images/P/0743206045',
 'http://images.amazon.com/images/P/0446394521',
 'http://images.amazon.com/images/P/0515131229',
 'http://images.amazon.com/images/P/0449134482',
 'http://images.amazon.com/images/P/0553293176',
 'http://images.amazon.com/images/P/0671525433',
 'http://images.amazon.com/images/P/0553561618',
 'http://images.amazon.com/images/P/034539657X',
 'http://images.amazon.com/images/P/0671670689',
 'http://images.amazon.com/images/P/1551666839',
 'http://images.amazon.com/images/P/0684841185',
 'http://images.amazon.com/images/P/0425147584',
 'http://images.amazon.com/images/P/0671027387',
 'http://images.amazon.com/images/P/0743418131',
 'http://images.amazon.com/images/P/034538184X',
 'http://images.amazon.com/images/P/0671011367',
 'http://images.amazon.com/images/P/0451188462',
 'http://images.amazon.com/images/P/0446359750',
 'http://images.amazon.com/images/P/0451124340',
 'http://images.amazon.com/images/P/0312995423',
 'http://images.amazon.com/images/P/0345391055',
 'http://images.amazon.com/images/P/0060928336',
 'http://images.amazon.com/images/P/0451177096',
 'http://images.amazon.com/images/P/0786889020',
 'http://images.amazon.com/images/P/0786881852',
 'http://images.amazon.com/images/P/006001203X',
 'http://images.amazon.com/images/P/0399137734',
 'http://images.amazon.com/images/P/0440215625',
 'http://images.amazon.com/images/P/055358264X',
 'http://images.amazon.com/images/P/0743211383',
 'http://images.amazon.com/images/P/0385502532',
 'http://images.amazon.com/images/P/0345439104',
 'http://images.amazon.com/images/P/044022425X',
 'http://images.amazon.com/images/P/0446532231',
 'http://images.amazon.com/images/P/0553582526',
 'http://images.amazon.com/images/P/0553560247',
 'http://images.amazon.com/images/P/0553279556',
 'http://images.amazon.com/images/P/039914613X',
 'http://images.amazon.com/images/P/0440122090',
 'http://images.amazon.com/images/P/0375703055',
 'http://images.amazon.com/images/P/0375726403',
 'http://images.amazon.com/images/P/0312853238',
 'http://images.amazon.com/images/P/0373218192',
 'http://images.amazon.com/images/P/0446611808',
 'http://images.amazon.com/images/P/0385318073',
 'http://images.amazon.com/images/P/0743457358',
 'http://images.amazon.com/images/P/0446604232',
 'http://images.amazon.com/images/P/0425158632',
 'http://images.amazon.com/images/P/0425132048',
 'http://images.amazon.com/images/P/0679429883',
 'http://images.amazon.com/images/P/0553284789',
 'http://images.amazon.com/images/P/0671894455',
 'http://images.amazon.com/images/P/051513287X',
 'http://images.amazon.com/images/P/3257208626',
 'http://images.amazon.com/images/P/0312983824',
 'http://images.amazon.com/images/P/0743237188',
 'http://images.amazon.com/images/P/0452283205',
 'http://images.amazon.com/images/P/0553580221',
 'http://images.amazon.com/images/P/0440124344',
 'http://images.amazon.com/images/P/0060938455',
 'http://images.amazon.com/images/P/0312252617',
 'http://images.amazon.com/images/P/0446605581',
 'http://images.amazon.com/images/P/0425145638',
 'http://images.amazon.com/images/P/0425097722',
 'http://images.amazon.com/images/P/0553579754',
 'http://images.amazon.com/images/P/0553582135',
 'http://images.amazon.com/images/P/0440200563',
 'http://images.amazon.com/images/P/1573229725',
 'http://images.amazon.com/images/P/0440222842',
 'http://images.amazon.com/images/P/0060958022',
 'http://images.amazon.com/images/P/0679459626',
 'http://images.amazon.com/images/P/067101420X',
 'http://images.amazon.com/images/P/0316678104',
 'http://images.amazon.com/images/P/0316781010',
 'http://images.amazon.com/images/P/0345368754',
 'http://images.amazon.com/images/P/0316693006',
 'http://images.amazon.com/images/P/0451170385',
 'http://images.amazon.com/images/P/0312966970',
 'http://images.amazon.com/images/P/0070212570',
 'http://images.amazon.com/images/P/0425154092',
 'http://images.amazon.com/images/P/0553582747',
 'http://images.amazon.com/images/P/0312983271',
 'http://images.amazon.com/images/P/031298328X',
 'http://images.amazon.com/images/P/0449219364',
 'http://images.amazon.com/images/P/067164257X',
 'http://images.amazon.com/images/P/0451176464',
 'http://images.amazon.com/images/P/1565115430',
 'http://images.amazon.com/images/P/0452282152',
 'http://images.amazon.com/images/P/0679746048',
 'http://images.amazon.com/images/P/0441003257',
 'http://images.amazon.com/images/P/0743418174',
 'http://images.amazon.com/images/P/0345298349',
 'http://images.amazon.com/images/P/0440224829',
 'http://images.amazon.com/images/P/0440213991',
 'http://images.amazon.com/images/P/0441304834',
 'http://images.amazon.com/images/P/0553564528',
 'http://images.amazon.com/images/P/0449219461',
 'http://images.amazon.com/images/P/0440224675',
 'http://images.amazon.com/images/P/0312983867',
 'http://images.amazon.com/images/P/0439064872',
 'http://images.amazon.com/images/P/0439139597',
 'http://images.amazon.com/images/P/043935806X',
 'http://images.amazon.com/images/P/0439136350',
 'http://images.amazon.com/images/P/0590353403',
 'http://images.amazon.com/images/P/059035342X',
 'http://images.amazon.com/images/P/0440208912',
 'http://images.amazon.com/images/P/0515128554',
 'http://images.amazon.com/images/P/0385299087',
 'http://images.amazon.com/images/P/0671034006',
 'http://images.amazon.com/images/P/0671024248',
 'http://images.amazon.com/images/P/0743436210',
 'http://images.amazon.com/images/P/0515132020',
 'http://images.amazon.com/images/P/0515133302',
 'http://images.amazon.com/images/P/0425167313',
 'http://images.amazon.com/images/P/0446603716',
 'http://images.amazon.com/images/P/042513525X',
 'http://images.amazon.com/images/P/1573225517',
 'http://images.amazon.com/images/P/0312971346',
 'http://images.amazon.com/images/P/0440414806',
 'http://images.amazon.com/images/P/0449702545',
 'http://images.amazon.com/images/P/0399143874',
 'http://images.amazon.com/images/P/0399142282',
 'http://images.amazon.com/images/P/0312976275',
 'http://images.amazon.com/images/P/0375727345',
 'http://images.amazon.com/images/P/0451197410',
 'http://images.amazon.com/images/P/1573229326',
 'http://images.amazon.com/images/P/0345370805',
 'http://images.amazon.com/images/P/031231616X',
 'http://images.amazon.com/images/P/0449221512',
 'http://images.amazon.com/images/P/0060987561',
 'http://images.amazon.com/images/P/0060391626',
 'http://images.amazon.com/images/P/0553279378',
 'http://images.amazon.com/images/P/0671888587',
 'http://images.amazon.com/images/P/0553582909',
 'http://images.amazon.com/images/P/0142000205',
 'http://images.amazon.com/images/P/0743406176',
 'http://images.amazon.com/images/P/0446329894',
 'http://images.amazon.com/images/P/0451204301',
 'http://images.amazon.com/images/P/0743418190',
 'http://images.amazon.com/images/P/0515124214',
 'http://images.amazon.com/images/P/0670855030',
 'http://images.amazon.com/images/P/0345384369',
 'http://images.amazon.com/images/P/0345337662',
 'http://images.amazon.com/images/P/0385494785',
 'http://images.amazon.com/images/P/0385486804',
 'http://images.amazon.com/images/P/0425155404',
 'http://images.amazon.com/images/P/0373484003',
 'http://images.amazon.com/images/P/0425182908',
 'http://images.amazon.com/images/P/0450411435',
 'http://images.amazon.com/images/P/0394580567',
 'http://images.amazon.com/images/P/0380710722',
 'http://images.amazon.com/images/P/0449221482',
 'http://images.amazon.com/images/P/0446604801',
 'http://images.amazon.com/images/P/0380564998',
 'http://images.amazon.com/images/P/0767905180',
 'http://images.amazon.com/images/P/0671038184',
 'http://images.amazon.com/images/P/0671042572',
 'http://images.amazon.com/images/P/0515126772',
 'http://images.amazon.com/images/P/0449218473',
 'http://images.amazon.com/images/P/0345370775',
 'http://images.amazon.com/images/P/0449221504',
 'http://images.amazon.com/images/P/0884092097',
 'http://images.amazon.com/images/P/0515136379',
 'http://images.amazon.com/images/P/051513628X',
 'http://images.amazon.com/images/P/0515136530',
 'http://images.amazon.com/images/P/0345453816',
 'http://images.amazon.com/images/P/0446601241',
 'http://images.amazon.com/images/P/0449221490',
 'http://images.amazon.com/images/P/0679441557',
 'http://images.amazon.com/images/P/0140099832',
 'http://images.amazon.com/images/P/0140092323',
 'http://images.amazon.com/images/P/0380813815',
 'http://images.amazon.com/images/P/0060086246',
 'http://images.amazon.com/images/P/0446525804',
 'http://images.amazon.com/images/P/0842329129',
 'http://images.amazon.com/images/P/0671568175',
 'http://images.amazon.com/images/P/0151008116',
 'http://images.amazon.com/images/P/0425115801',
 'http://images.amazon.com/images/P/038542017X',
 'http://images.amazon.com/images/P/0385474016',
 'http://images.amazon.com/images/P/0385420161',
 'http://images.amazon.com/images/P/0060976845',
 'http://images.amazon.com/images/P/0553571818',
 'http://images.amazon.com/images/P/0399501487',
 'http://images.amazon.com/images/P/0140119906',
 'http://images.amazon.com/images/P/0671758896',
 'http://images.amazon.com/images/P/0316096199',
 'http://images.amazon.com/images/P/0786867647',
 'http://images.amazon.com/images/P/0449223604',
 'http://images.amazon.com/images/P/0373483503',
 'http://images.amazon.com/images/P/0373483694',
 'http://images.amazon.com/images/P/0446802204',
 'http://images.amazon.com/images/P/014034294X',
 'http://images.amazon.com/images/P/0316776963',
 'http://images.amazon.com/images/P/006016848X',
 'http://images.amazon.com/images/P/0671034022',
 'http://images.amazon.com/images/P/0440209412',
 'http://images.amazon.com/images/P/0446523569',
 'http://images.amazon.com/images/P/0312422156',
 'http://images.amazon.com/images/P/0425118703',
 'http://images.amazon.com/images/P/0399148248',
 'http://images.amazon.com/images/P/0679751521',
 'http://images.amazon.com/images/P/0679429220',
 'http://images.amazon.com/images/P/0375706771',
 'http://images.amazon.com/images/P/0425152898',
 'http://images.amazon.com/images/P/0440224772',
 'http://images.amazon.com/images/P/0451153553',
 'http://images.amazon.com/images/P/0688177751',
 'http://images.amazon.com/images/P/0345413873',
 'http://images.amazon.com/images/P/0515120618',
 'http://images.amazon.com/images/P/0449910237',
 'http://images.amazon.com/images/P/0671867113',
 'http://images.amazon.com/images/P/1400031362',
 'http://images.amazon.com/images/P/0451180410',
 'http://images.amazon.com/images/P/0425189864',
 'http://images.amazon.com/images/P/0786866276',
 'http://images.amazon.com/images/P/0425144429',
 'http://images.amazon.com/images/P/0684832291',
 'http://images.amazon.com/images/P/0380731851',
 'http://images.amazon.com/images/P/0449223612',
 'http://images.amazon.com/images/P/0316777730',
 'http://images.amazon.com/images/P/0451178599',
 'http://images.amazon.com/images/P/0440241162',
 'http://images.amazon.com/images/P/0441569595',
 'http://images.amazon.com/images/P/0380789019',
 'http://images.amazon.com/images/P/0805063897',
 'http://images.amazon.com/images/P/0842329242',
 'http://images.amazon.com/images/P/0553272535',
 'http://images.amazon.com/images/P/0425146413',
 'http://images.amazon.com/images/P/055356451X',
 'http://images.amazon.com/images/P/0671525743',
 'http://images.amazon.com/images/P/0451180232',
 'http://images.amazon.com/images/P/0446531332',
 'http://images.amazon.com/images/P/0836278658',
 'http://images.amazon.com/images/P/0345404777',
 'http://images.amazon.com/images/P/0380727501',
 'http://images.amazon.com/images/P/0688084915',
 'http://images.amazon.com/images/P/0743482891',
 'http://images.amazon.com/images/P/0671004530',
 'http://images.amazon.com/images/P/0553582755',
 'http://images.amazon.com/images/P/067940712X',
 'http://images.amazon.com/images/P/0312990456',
 'http://images.amazon.com/images/P/0061009059',
 'http://images.amazon.com/images/P/0385503857',
 'http://images.amazon.com/images/P/0440222915',
 'http://images.amazon.com/images/P/0451152190',
 'http://images.amazon.com/images/P/0449003795',
 'http://images.amazon.com/images/P/0679433740',
 'http://images.amazon.com/images/P/0425109720',
 'http://images.amazon.com/images/P/0743412028',
 'http://images.amazon.com/images/P/0802139256',
 'http://images.amazon.com/images/P/0451162072',
 'http://images.amazon.com/images/P/0425101452',
 'http://images.amazon.com/images/P/0060168013',
 'http://images.amazon.com/images/P/0375705856',
 'http://images.amazon.com/images/P/0446365505',
 'http://images.amazon.com/images/P/0446605409',
 'http://images.amazon.com/images/P/0425169863',
 'http://images.amazon.com/images/P/002542730X',
 'http://images.amazon.com/images/P/0316693286',
 'http://images.amazon.com/images/P/0425189031',
 'http://images.amazon.com/images/P/0679735909',
 'http://images.amazon.com/images/P/0380710218',
 'http://images.amazon.com/images/P/0425168468',
 'http://images.amazon.com/images/P/0446359866',
 'http://images.amazon.com/images/P/0671867156',
 'http://images.amazon.com/images/P/055321215X',
 'http://images.amazon.com/images/P/0679448594',
 'http://images.amazon.com/images/P/0553574671',
 'http://images.amazon.com/images/P/0060199652',

In [ ]:
book_names_list

In [761]:
len(get_link(book_names_list))

742

In [762]:
pickle.dump(ii,open('book_image.pkl','wb'))

In [609]:
requests.get('http://images.amazon.com/images/P/0195153448')